/* tslint:disable */
/* eslint-disable */
/**
 * Trip Planner
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 10.6.21.17
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
import type { AdditionalInfoResponseTimestampsAvailability } from "./AdditionalInfoResponseTimestampsAvailability";
import {
    AdditionalInfoResponseTimestampsAvailabilityFromJSON,
    AdditionalInfoResponseTimestampsAvailabilityFromJSONTyped,
    AdditionalInfoResponseTimestampsAvailabilityToJSON,
    AdditionalInfoResponseTimestampsAvailabilityToJSONTyped,
} from "./AdditionalInfoResponseTimestampsAvailability";
import type { AdditionalInfoResponseTimestampsValidityInner } from "./AdditionalInfoResponseTimestampsValidityInner";
import {
    AdditionalInfoResponseTimestampsValidityInnerFromJSON,
    AdditionalInfoResponseTimestampsValidityInnerFromJSONTyped,
    AdditionalInfoResponseTimestampsValidityInnerToJSON,
    AdditionalInfoResponseTimestampsValidityInnerToJSONTyped,
} from "./AdditionalInfoResponseTimestampsValidityInner";

/**
 * This element describes timestamps for a service alert.
 * @export
 * @interface AdditionalInfoResponseTimestamps
 */
export interface AdditionalInfoResponseTimestamps {
    /**
     *
     * @type {AdditionalInfoResponseTimestampsAvailability}
     * @memberof AdditionalInfoResponseTimestamps
     */
    availability?: AdditionalInfoResponseTimestampsAvailability;
    /**
     * A timestamp in `YYYY-MM-DDTHH:MM:SSZ` format that indicates when the alert was created.
     * @type {string}
     * @memberof AdditionalInfoResponseTimestamps
     */
    creation?: string;
    /**
     * A timestamp in `YYYY-MM-DDTHH:MM:SSZ` format that indicates when the alert was last modified.
     * @type {string}
     * @memberof AdditionalInfoResponseTimestamps
     */
    lastModification?: string;
    /**
     * This describes when the incident is actually occurring.
     *
     * @type {Array<AdditionalInfoResponseTimestampsValidityInner>}
     * @memberof AdditionalInfoResponseTimestamps
     */
    validity?: Array<AdditionalInfoResponseTimestampsValidityInner>;
}

/**
 * Check if a given object implements the AdditionalInfoResponseTimestamps interface.
 */
export function instanceOfAdditionalInfoResponseTimestamps(
    value: object
): value is AdditionalInfoResponseTimestamps {
    return true;
}

export function AdditionalInfoResponseTimestampsFromJSON(
    json: any
): AdditionalInfoResponseTimestamps {
    return AdditionalInfoResponseTimestampsFromJSONTyped(json, false);
}

export function AdditionalInfoResponseTimestampsFromJSONTyped(
    json: any,
    ignoreDiscriminator: boolean
): AdditionalInfoResponseTimestamps {
    if (json == null) {
        return json;
    }
    return {
        availability:
            json["availability"] == null
                ? undefined
                : AdditionalInfoResponseTimestampsAvailabilityFromJSON(json["availability"]),
        creation: json["creation"] == null ? undefined : json["creation"],
        lastModification: json["lastModification"] == null ? undefined : json["lastModification"],
        validity:
            json["validity"] == null
                ? undefined
                : (json["validity"] as Array<any>).map(
                      AdditionalInfoResponseTimestampsValidityInnerFromJSON
                  ),
    };
}

export function AdditionalInfoResponseTimestampsToJSON(
    json: any
): AdditionalInfoResponseTimestamps {
    return AdditionalInfoResponseTimestampsToJSONTyped(json, false);
}

export function AdditionalInfoResponseTimestampsToJSONTyped(
    value?: AdditionalInfoResponseTimestamps | null,
    ignoreDiscriminator: boolean = false
): any {
    if (value == null) {
        return value;
    }

    return {
        availability: AdditionalInfoResponseTimestampsAvailabilityToJSON(value["availability"]),
        creation: value["creation"],
        lastModification: value["lastModification"],
        validity:
            value["validity"] == null
                ? undefined
                : (value["validity"] as Array<any>).map(
                      AdditionalInfoResponseTimestampsValidityInnerToJSON
                  ),
    };
}
