/* tslint:disable */
/* eslint-disable */
/**
 * Trip Planner
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 10.6.21.17
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
/**
 *
 * @export
 * @interface AdditionalInfoResponseTimestampsValidityInner
 */
export interface AdditionalInfoResponseTimestampsValidityInner {
    /**
     * A timestamp in `YYYY-MM-DDTHH:MM:SSZ` format that indicates the starting date and time of this date range.
     * @type {string}
     * @memberof AdditionalInfoResponseTimestampsValidityInner
     */
    from?: string;
    /**
     * A timestamp in `YYYY-MM-DDTHH:MM:SSZ` format that indicates the ending date and time of this date range.
     * @type {string}
     * @memberof AdditionalInfoResponseTimestampsValidityInner
     */
    to?: string;
}

/**
 * Check if a given object implements the AdditionalInfoResponseTimestampsValidityInner interface.
 */
export function instanceOfAdditionalInfoResponseTimestampsValidityInner(
    value: object
): value is AdditionalInfoResponseTimestampsValidityInner {
    return true;
}

export function AdditionalInfoResponseTimestampsValidityInnerFromJSON(
    json: any
): AdditionalInfoResponseTimestampsValidityInner {
    return AdditionalInfoResponseTimestampsValidityInnerFromJSONTyped(json, false);
}

export function AdditionalInfoResponseTimestampsValidityInnerFromJSONTyped(
    json: any,
    ignoreDiscriminator: boolean
): AdditionalInfoResponseTimestampsValidityInner {
    if (json == null) {
        return json;
    }
    return {
        from: json["from"] == null ? undefined : json["from"],
        to: json["to"] == null ? undefined : json["to"],
    };
}

export function AdditionalInfoResponseTimestampsValidityInnerToJSON(
    json: any
): AdditionalInfoResponseTimestampsValidityInner {
    return AdditionalInfoResponseTimestampsValidityInnerToJSONTyped(json, false);
}

export function AdditionalInfoResponseTimestampsValidityInnerToJSONTyped(
    value?: AdditionalInfoResponseTimestampsValidityInner | null,
    ignoreDiscriminator: boolean = false
): any {
    if (value == null) {
        return value;
    }

    return {
        from: value["from"],
        to: value["to"],
    };
}
