/* tslint:disable */
/* eslint-disable */
/**
 * Trip Planner
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 10.6.21.17
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
/**
 * This element describes the destination of trips fulfilled by the given line.
 * @export
 * @interface AdditionalInfoResponseAffectedLineDestination
 */
export interface AdditionalInfoResponseAffectedLineDestination {
    /**
     * This is the name of the destination.
     * @type {string}
     * @memberof AdditionalInfoResponseAffectedLineDestination
     */
    name?: string;
    /**
     * The type of the location the destination is.
     * @type {string}
     * @memberof AdditionalInfoResponseAffectedLineDestination
     */
    type?: AdditionalInfoResponseAffectedLineDestinationTypeEnum;
}

/**
 * @export
 */
export const AdditionalInfoResponseAffectedLineDestinationTypeEnum = {
    Poi: "poi",
    Singlehouse: "singlehouse",
    Stop: "stop",
    Platform: "platform",
    Street: "street",
    Locality: "locality",
    Suburb: "suburb",
    GisPoint: "gisPoint",
    Unknown: "unknown",
} as const;
export type AdditionalInfoResponseAffectedLineDestinationTypeEnum =
    (typeof AdditionalInfoResponseAffectedLineDestinationTypeEnum)[keyof typeof AdditionalInfoResponseAffectedLineDestinationTypeEnum];

/**
 * Check if a given object implements the AdditionalInfoResponseAffectedLineDestination interface.
 */
export function instanceOfAdditionalInfoResponseAffectedLineDestination(
    value: object
): value is AdditionalInfoResponseAffectedLineDestination {
    return true;
}

export function AdditionalInfoResponseAffectedLineDestinationFromJSON(
    json: any
): AdditionalInfoResponseAffectedLineDestination {
    return AdditionalInfoResponseAffectedLineDestinationFromJSONTyped(json, false);
}

export function AdditionalInfoResponseAffectedLineDestinationFromJSONTyped(
    json: any,
    ignoreDiscriminator: boolean
): AdditionalInfoResponseAffectedLineDestination {
    if (json == null) {
        return json;
    }
    return {
        name: json["name"] == null ? undefined : json["name"],
        type: json["type"] == null ? undefined : json["type"],
    };
}

export function AdditionalInfoResponseAffectedLineDestinationToJSON(
    json: any
): AdditionalInfoResponseAffectedLineDestination {
    return AdditionalInfoResponseAffectedLineDestinationToJSONTyped(json, false);
}

export function AdditionalInfoResponseAffectedLineDestinationToJSONTyped(
    value?: AdditionalInfoResponseAffectedLineDestination | null,
    ignoreDiscriminator: boolean = false
): any {
    if (value == null) {
        return value;
    }

    return {
        name: value["name"],
        type: value["type"],
    };
}
