/* tslint:disable */
/* eslint-disable */
/**
 * Trip Planner
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 10.6.21.17
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
import type { AdditionalInfoResponseMessagePropertiesSource } from "./AdditionalInfoResponseMessagePropertiesSource";
import {
    AdditionalInfoResponseMessagePropertiesSourceFromJSON,
    AdditionalInfoResponseMessagePropertiesSourceFromJSONTyped,
    AdditionalInfoResponseMessagePropertiesSourceToJSON,
    AdditionalInfoResponseMessagePropertiesSourceToJSONTyped,
} from "./AdditionalInfoResponseMessagePropertiesSource";

/**
 * This element contains a additional information about the alert.
 *
 * @export
 * @interface AdditionalInfoResponseMessageProperties
 */
export interface AdditionalInfoResponseMessageProperties {
    /**
     * This field uniquely identifies which operator or organisation entered the alert into the system.
     *
     * @type {string}
     * @memberof AdditionalInfoResponseMessageProperties
     */
    providerCode?: string;
    /**
     * This is a plaintext summary of the alert content, although note that it may contain HTML entities such as &nbsp;.
     *
     * @type {string}
     * @memberof AdditionalInfoResponseMessageProperties
     */
    smsText?: string;
    /**
     *
     * @type {AdditionalInfoResponseMessagePropertiesSource}
     * @memberof AdditionalInfoResponseMessageProperties
     */
    source?: AdditionalInfoResponseMessagePropertiesSource;
}

/**
 * Check if a given object implements the AdditionalInfoResponseMessageProperties interface.
 */
export function instanceOfAdditionalInfoResponseMessageProperties(
    value: object
): value is AdditionalInfoResponseMessageProperties {
    return true;
}

export function AdditionalInfoResponseMessagePropertiesFromJSON(
    json: any
): AdditionalInfoResponseMessageProperties {
    return AdditionalInfoResponseMessagePropertiesFromJSONTyped(json, false);
}

export function AdditionalInfoResponseMessagePropertiesFromJSONTyped(
    json: any,
    ignoreDiscriminator: boolean
): AdditionalInfoResponseMessageProperties {
    if (json == null) {
        return json;
    }
    return {
        providerCode: json["providerCode"] == null ? undefined : json["providerCode"],
        smsText: json["smsText"] == null ? undefined : json["smsText"],
        source:
            json["source"] == null
                ? undefined
                : AdditionalInfoResponseMessagePropertiesSourceFromJSON(json["source"]),
    };
}

export function AdditionalInfoResponseMessagePropertiesToJSON(
    json: any
): AdditionalInfoResponseMessageProperties {
    return AdditionalInfoResponseMessagePropertiesToJSONTyped(json, false);
}

export function AdditionalInfoResponseMessagePropertiesToJSONTyped(
    value?: AdditionalInfoResponseMessageProperties | null,
    ignoreDiscriminator: boolean = false
): any {
    if (value == null) {
        return value;
    }

    return {
        providerCode: value["providerCode"],
        smsText: value["smsText"],
        source: AdditionalInfoResponseMessagePropertiesSourceToJSON(value["source"]),
    };
}
