/* tslint:disable */
/* eslint-disable */
/**
 * Trip Planner
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 10.6.21.17
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
/**
 * Contains information about who created this alert.
 * @export
 * @interface AdditionalInfoResponseMessagePropertiesSource
 */
export interface AdditionalInfoResponseMessagePropertiesSource {
    /**
     * A unique identifier for the creator of this alert.
     * @type {string}
     * @memberof AdditionalInfoResponseMessagePropertiesSource
     */
    id?: string;
    /**
     * The name of the creator of this alert.
     * @type {string}
     * @memberof AdditionalInfoResponseMessagePropertiesSource
     */
    name?: string;
    /**
     * The type of system of the alert creator.
     * @type {string}
     * @memberof AdditionalInfoResponseMessagePropertiesSource
     */
    type?: string;
}

/**
 * Check if a given object implements the AdditionalInfoResponseMessagePropertiesSource interface.
 */
export function instanceOfAdditionalInfoResponseMessagePropertiesSource(
    value: object
): value is AdditionalInfoResponseMessagePropertiesSource {
    return true;
}

export function AdditionalInfoResponseMessagePropertiesSourceFromJSON(
    json: any
): AdditionalInfoResponseMessagePropertiesSource {
    return AdditionalInfoResponseMessagePropertiesSourceFromJSONTyped(json, false);
}

export function AdditionalInfoResponseMessagePropertiesSourceFromJSONTyped(
    json: any,
    ignoreDiscriminator: boolean
): AdditionalInfoResponseMessagePropertiesSource {
    if (json == null) {
        return json;
    }
    return {
        id: json["id"] == null ? undefined : json["id"],
        name: json["name"] == null ? undefined : json["name"],
        type: json["type"] == null ? undefined : json["type"],
    };
}

export function AdditionalInfoResponseMessagePropertiesSourceToJSON(
    json: any
): AdditionalInfoResponseMessagePropertiesSource {
    return AdditionalInfoResponseMessagePropertiesSourceToJSONTyped(json, false);
}

export function AdditionalInfoResponseMessagePropertiesSourceToJSONTyped(
    value?: AdditionalInfoResponseMessagePropertiesSource | null,
    ignoreDiscriminator: boolean = false
): any {
    if (value == null) {
        return value;
    }

    return {
        id: value["id"],
        name: value["name"],
        type: value["type"],
    };
}
