/* tslint:disable */
/* eslint-disable */
/**
 * Trip Planner
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 10.6.21.17
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
import type { ParentLocation } from "./ParentLocation";
import {
    ParentLocationFromJSON,
    ParentLocationFromJSONTyped,
    ParentLocationToJSON,
    ParentLocationToJSONTyped,
} from "./ParentLocation";

/**
 * This element describes a single stop that is affected by a service alert.
 * @export
 * @interface AdditionalInfoResponseAffectedStop
 */
export interface AdditionalInfoResponseAffectedStop {
    /**
     * This the unique ID of the stop that is affected. It is the same ID that is
     * used elsewhere in the system, such as in `trip` or
     * `stop_finder`.
     *
     * @type {string}
     * @memberof AdditionalInfoResponseAffectedStop
     */
    id?: string;
    /**
     * This is the title of the affected stop.
     * @type {string}
     * @memberof AdditionalInfoResponseAffectedStop
     */
    name?: string;
    /**
     *
     * @type {ParentLocation}
     * @memberof AdditionalInfoResponseAffectedStop
     */
    parent?: ParentLocation;
    /**
     * The type of the location that is affected.
     * @type {string}
     * @memberof AdditionalInfoResponseAffectedStop
     */
    type?: AdditionalInfoResponseAffectedStopTypeEnum;
}

/**
 * @export
 */
export const AdditionalInfoResponseAffectedStopTypeEnum = {
    Poi: "poi",
    Singlehouse: "singlehouse",
    Stop: "stop",
    Platform: "platform",
    Street: "street",
    Locality: "locality",
    Suburb: "suburb",
    GisPoint: "gisPoint",
    Unknown: "unknown",
} as const;
export type AdditionalInfoResponseAffectedStopTypeEnum =
    (typeof AdditionalInfoResponseAffectedStopTypeEnum)[keyof typeof AdditionalInfoResponseAffectedStopTypeEnum];

/**
 * Check if a given object implements the AdditionalInfoResponseAffectedStop interface.
 */
export function instanceOfAdditionalInfoResponseAffectedStop(
    value: object
): value is AdditionalInfoResponseAffectedStop {
    return true;
}

export function AdditionalInfoResponseAffectedStopFromJSON(
    json: any
): AdditionalInfoResponseAffectedStop {
    return AdditionalInfoResponseAffectedStopFromJSONTyped(json, false);
}

export function AdditionalInfoResponseAffectedStopFromJSONTyped(
    json: any,
    ignoreDiscriminator: boolean
): AdditionalInfoResponseAffectedStop {
    if (json == null) {
        return json;
    }
    return {
        id: json["id"] == null ? undefined : json["id"],
        name: json["name"] == null ? undefined : json["name"],
        parent: json["parent"] == null ? undefined : ParentLocationFromJSON(json["parent"]),
        type: json["type"] == null ? undefined : json["type"],
    };
}

export function AdditionalInfoResponseAffectedStopToJSON(
    json: any
): AdditionalInfoResponseAffectedStop {
    return AdditionalInfoResponseAffectedStopToJSONTyped(json, false);
}

export function AdditionalInfoResponseAffectedStopToJSONTyped(
    value?: AdditionalInfoResponseAffectedStop | null,
    ignoreDiscriminator: boolean = false
): any {
    if (value == null) {
        return value;
    }

    return {
        id: value["id"],
        name: value["name"],
        parent: ParentLocationToJSON(value["parent"]),
        type: value["type"],
    };
}
