/* tslint:disable */
/* eslint-disable */
/**
 * Trip Planner
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 10.6.21.17
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
import type { AdditionalInfoResponseMessageProperties } from "./AdditionalInfoResponseMessageProperties";
import {
    AdditionalInfoResponseMessagePropertiesFromJSON,
    AdditionalInfoResponseMessagePropertiesFromJSONTyped,
    AdditionalInfoResponseMessagePropertiesToJSON,
    AdditionalInfoResponseMessagePropertiesToJSONTyped,
} from "./AdditionalInfoResponseMessageProperties";
import type { AdditionalInfoResponseTimestamps } from "./AdditionalInfoResponseTimestamps";
import {
    AdditionalInfoResponseTimestampsFromJSON,
    AdditionalInfoResponseTimestampsFromJSONTyped,
    AdditionalInfoResponseTimestampsToJSON,
    AdditionalInfoResponseTimestampsToJSONTyped,
} from "./AdditionalInfoResponseTimestamps";
import type { AdditionalInfoResponseMessageAffected } from "./AdditionalInfoResponseMessageAffected";
import {
    AdditionalInfoResponseMessageAffectedFromJSON,
    AdditionalInfoResponseMessageAffectedFromJSONTyped,
    AdditionalInfoResponseMessageAffectedToJSON,
    AdditionalInfoResponseMessageAffectedToJSONTyped,
} from "./AdditionalInfoResponseMessageAffected";

/**
 * This element describes a single service alert.
 * @export
 * @interface AdditionalInfoResponseMessage
 */
export interface AdditionalInfoResponseMessage {
    /**
     *
     * @type {AdditionalInfoResponseMessageAffected}
     * @memberof AdditionalInfoResponseMessage
     */
    affected?: AdditionalInfoResponseMessageAffected;
    /**
     * This is the descriptive alert content. It may contain HTML tags and/or HTML entities.
     *
     * @type {string}
     * @memberof AdditionalInfoResponseMessage
     */
    content?: string;
    /**
     * This is a unique identifier for this particular service alert.
     *
     * @type {string}
     * @memberof AdditionalInfoResponseMessage
     */
    id?: string;
    /**
     * This value indicates how important the service alert is. A value of `high` or `veryHigh` likely indicates that
     * the alert will correspond to an event that impacts the ability to travel for relevant users, while `low` or `veryLow`
     * might be more of an informational message.
     *
     * @type {string}
     * @memberof AdditionalInfoResponseMessage
     */
    priority?: AdditionalInfoResponseMessagePriorityEnum;
    /**
     *
     * @type {AdditionalInfoResponseMessageProperties}
     * @memberof AdditionalInfoResponseMessage
     */
    properties?: AdditionalInfoResponseMessageProperties;
    /**
     * This is short summary that can be used as a heading for the alert content. It may contain HTML tags and/or HTML entities.
     *
     * @type {string}
     * @memberof AdditionalInfoResponseMessage
     */
    subtitle?: string;
    /**
     *
     * @type {AdditionalInfoResponseTimestamps}
     * @memberof AdditionalInfoResponseMessage
     */
    timestamps?: AdditionalInfoResponseTimestamps;
    /**
     * This indicates the category of the service alert. For example, if this value is `stopInfo`, then the alert is
     * related to an issue affecting a stop. It is then likely that the affected lines would be those that stop at
     * the affected stop.
     *
     * * `routeInfo`: The alert is related to a specific route
     * * `stopInfo`: The alert is related to a specific stop
     * * `stopBlocking`: This alert is related to a stop closure
     * * `lineInfo`: The alert is related to a specific journey
     * * `bannerInfo`: The alert of high importance and potentially has a network-wide impact.
     *
     * @type {string}
     * @memberof AdditionalInfoResponseMessage
     */
    type?: AdditionalInfoResponseMessageTypeEnum;
    /**
     * This field contains a URL that contains additional information about the alert.
     * @type {string}
     * @memberof AdditionalInfoResponseMessage
     */
    url?: string;
    /**
     * This field contains a title that can be used when displaying the `infoLinkURL` URL.
     * @type {string}
     * @memberof AdditionalInfoResponseMessage
     */
    urlText?: string;
    /**
     * This number indicates the version of this alert. Initially when it is created it has version `1`, but if it is then
     * updated it will have a new `lastModification` value and the version will now be `2`.
     *
     * @type {number}
     * @memberof AdditionalInfoResponseMessage
     */
    version?: number;
}

/**
 * @export
 */
export const AdditionalInfoResponseMessagePriorityEnum = {
    VeryLow: "veryLow",
    Low: "low",
    Normal: "normal",
    High: "high",
    VeryHigh: "veryHigh",
} as const;
export type AdditionalInfoResponseMessagePriorityEnum =
    (typeof AdditionalInfoResponseMessagePriorityEnum)[keyof typeof AdditionalInfoResponseMessagePriorityEnum];

/**
 * @export
 */
export const AdditionalInfoResponseMessageTypeEnum = {
    RouteInfo: "routeInfo",
    StopInfo: "stopInfo",
    LineInfo: "lineInfo",
    BannerInfo: "bannerInfo",
    StopBlocking: "stopBlocking",
} as const;
export type AdditionalInfoResponseMessageTypeEnum =
    (typeof AdditionalInfoResponseMessageTypeEnum)[keyof typeof AdditionalInfoResponseMessageTypeEnum];

/**
 * Check if a given object implements the AdditionalInfoResponseMessage interface.
 */
export function instanceOfAdditionalInfoResponseMessage(
    value: object
): value is AdditionalInfoResponseMessage {
    return true;
}

export function AdditionalInfoResponseMessageFromJSON(json: any): AdditionalInfoResponseMessage {
    return AdditionalInfoResponseMessageFromJSONTyped(json, false);
}

export function AdditionalInfoResponseMessageFromJSONTyped(
    json: any,
    ignoreDiscriminator: boolean
): AdditionalInfoResponseMessage {
    if (json == null) {
        return json;
    }
    return {
        affected:
            json["affected"] == null
                ? undefined
                : AdditionalInfoResponseMessageAffectedFromJSON(json["affected"]),
        content: json["content"] == null ? undefined : json["content"],
        id: json["id"] == null ? undefined : json["id"],
        priority: json["priority"] == null ? undefined : json["priority"],
        properties:
            json["properties"] == null
                ? undefined
                : AdditionalInfoResponseMessagePropertiesFromJSON(json["properties"]),
        subtitle: json["subtitle"] == null ? undefined : json["subtitle"],
        timestamps:
            json["timestamps"] == null
                ? undefined
                : AdditionalInfoResponseTimestampsFromJSON(json["timestamps"]),
        type: json["type"] == null ? undefined : json["type"],
        url: json["url"] == null ? undefined : json["url"],
        urlText: json["urlText"] == null ? undefined : json["urlText"],
        version: json["version"] == null ? undefined : json["version"],
    };
}

export function AdditionalInfoResponseMessageToJSON(json: any): AdditionalInfoResponseMessage {
    return AdditionalInfoResponseMessageToJSONTyped(json, false);
}

export function AdditionalInfoResponseMessageToJSONTyped(
    value?: AdditionalInfoResponseMessage | null,
    ignoreDiscriminator: boolean = false
): any {
    if (value == null) {
        return value;
    }

    return {
        affected: AdditionalInfoResponseMessageAffectedToJSON(value["affected"]),
        content: value["content"],
        id: value["id"],
        priority: value["priority"],
        properties: AdditionalInfoResponseMessagePropertiesToJSON(value["properties"]),
        subtitle: value["subtitle"],
        timestamps: AdditionalInfoResponseTimestampsToJSON(value["timestamps"]),
        type: value["type"],
        url: value["url"],
        urlText: value["urlText"],
        version: value["version"],
    };
}
