/* tslint:disable */
/* eslint-disable */
/**
 * Trip Planner
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 10.6.21.17
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
import type { ApiErrorResponse } from "./ApiErrorResponse";
import {
    ApiErrorResponseFromJSON,
    ApiErrorResponseFromJSONTyped,
    ApiErrorResponseToJSON,
    ApiErrorResponseToJSONTyped,
} from "./ApiErrorResponse";
import type { AdditionalInfoResponseInfos } from "./AdditionalInfoResponseInfos";
import {
    AdditionalInfoResponseInfosFromJSON,
    AdditionalInfoResponseInfosFromJSONTyped,
    AdditionalInfoResponseInfosToJSON,
    AdditionalInfoResponseInfosToJSONTyped,
} from "./AdditionalInfoResponseInfos";

/**
 * This is the response data returned when performing an `add_info` request.
 *
 * @export
 * @interface AdditionalInfoResponse
 */
export interface AdditionalInfoResponse {
    /**
     *
     * @type {ApiErrorResponse}
     * @memberof AdditionalInfoResponse
     */
    error?: ApiErrorResponse;
    /**
     *
     * @type {AdditionalInfoResponseInfos}
     * @memberof AdditionalInfoResponse
     */
    infos?: AdditionalInfoResponseInfos;
    /**
     * A timestamp in `YYYY-MM-DDTHH:MM:SSZ` format
     * @type {string}
     * @memberof AdditionalInfoResponse
     */
    timestamp?: string;
    /**
     * The version of the API that provided the response. Note that if this value is different to above, then the returned data may be
     * different than expected. You can set the expected version using the `version` request parameter.
     *
     * @type {string}
     * @memberof AdditionalInfoResponse
     */
    version?: string;
}

/**
 * Check if a given object implements the AdditionalInfoResponse interface.
 */
export function instanceOfAdditionalInfoResponse(value: object): value is AdditionalInfoResponse {
    return true;
}

export function AdditionalInfoResponseFromJSON(json: any): AdditionalInfoResponse {
    return AdditionalInfoResponseFromJSONTyped(json, false);
}

export function AdditionalInfoResponseFromJSONTyped(
    json: any,
    ignoreDiscriminator: boolean
): AdditionalInfoResponse {
    if (json == null) {
        return json;
    }
    return {
        error: json["error"] == null ? undefined : ApiErrorResponseFromJSON(json["error"]),
        infos:
            json["infos"] == null ? undefined : AdditionalInfoResponseInfosFromJSON(json["infos"]),
        timestamp: json["timestamp"] == null ? undefined : json["timestamp"],
        version: json["version"] == null ? undefined : json["version"],
    };
}

export function AdditionalInfoResponseToJSON(json: any): AdditionalInfoResponse {
    return AdditionalInfoResponseToJSONTyped(json, false);
}

export function AdditionalInfoResponseToJSONTyped(
    value?: AdditionalInfoResponse | null,
    ignoreDiscriminator: boolean = false
): any {
    if (value == null) {
        return value;
    }

    return {
        error: ApiErrorResponseToJSON(value["error"]),
        infos: AdditionalInfoResponseInfosToJSON(value["infos"]),
        timestamp: value["timestamp"],
        version: value["version"],
    };
}
