/* tslint:disable */
/* eslint-disable */
/**
 * Trip Planner
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 10.6.21.17
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
import type { AdditionalInfoResponseAffectedLineDestination } from "./AdditionalInfoResponseAffectedLineDestination";
import {
    AdditionalInfoResponseAffectedLineDestinationFromJSON,
    AdditionalInfoResponseAffectedLineDestinationFromJSONTyped,
    AdditionalInfoResponseAffectedLineDestinationToJSON,
    AdditionalInfoResponseAffectedLineDestinationToJSONTyped,
} from "./AdditionalInfoResponseAffectedLineDestination";
import type { RouteProduct } from "./RouteProduct";
import {
    RouteProductFromJSON,
    RouteProductFromJSONTyped,
    RouteProductToJSON,
    RouteProductToJSONTyped,
} from "./RouteProduct";

/**
 * This element describes a single route that is affected by a service alert.
 * @export
 * @interface AdditionalInfoResponseAffectedLine
 */
export interface AdditionalInfoResponseAffectedLine {
    /**
     *
     * @type {AdditionalInfoResponseAffectedLineDestination}
     * @memberof AdditionalInfoResponseAffectedLine
     */
    destination?: AdditionalInfoResponseAffectedLineDestination;
    /**
     * This is the unique ID that identifies the given line.
     * @type {string}
     * @memberof AdditionalInfoResponseAffectedLine
     */
    id?: string;
    /**
     * This is the full name of the route.
     * @type {string}
     * @memberof AdditionalInfoResponseAffectedLine
     */
    name?: string;
    /**
     * This is the short name or code of the route.
     * @type {string}
     * @memberof AdditionalInfoResponseAffectedLine
     */
    number?: string;
    /**
     *
     * @type {RouteProduct}
     * @memberof AdditionalInfoResponseAffectedLine
     */
    product?: RouteProduct;
}

/**
 * Check if a given object implements the AdditionalInfoResponseAffectedLine interface.
 */
export function instanceOfAdditionalInfoResponseAffectedLine(
    value: object
): value is AdditionalInfoResponseAffectedLine {
    return true;
}

export function AdditionalInfoResponseAffectedLineFromJSON(
    json: any
): AdditionalInfoResponseAffectedLine {
    return AdditionalInfoResponseAffectedLineFromJSONTyped(json, false);
}

export function AdditionalInfoResponseAffectedLineFromJSONTyped(
    json: any,
    ignoreDiscriminator: boolean
): AdditionalInfoResponseAffectedLine {
    if (json == null) {
        return json;
    }
    return {
        destination:
            json["destination"] == null
                ? undefined
                : AdditionalInfoResponseAffectedLineDestinationFromJSON(json["destination"]),
        id: json["id"] == null ? undefined : json["id"],
        name: json["name"] == null ? undefined : json["name"],
        number: json["number"] == null ? undefined : json["number"],
        product: json["product"] == null ? undefined : RouteProductFromJSON(json["product"]),
    };
}

export function AdditionalInfoResponseAffectedLineToJSON(
    json: any
): AdditionalInfoResponseAffectedLine {
    return AdditionalInfoResponseAffectedLineToJSONTyped(json, false);
}

export function AdditionalInfoResponseAffectedLineToJSONTyped(
    value?: AdditionalInfoResponseAffectedLine | null,
    ignoreDiscriminator: boolean = false
): any {
    if (value == null) {
        return value;
    }

    return {
        destination: AdditionalInfoResponseAffectedLineDestinationToJSON(value["destination"]),
        id: value["id"],
        name: value["name"],
        number: value["number"],
        product: RouteProductToJSON(value["product"]),
    };
}
