/* tslint:disable */
/* eslint-disable */
/**
 * Trip Planner
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 10.6.21.17
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
/**
 * This describes when the alert should published. Note that this is used as guidance only and your own
 * needs may vary.
 *
 * @export
 * @interface AdditionalInfoResponseTimestampsAvailability
 */
export interface AdditionalInfoResponseTimestampsAvailability {
    /**
     * A timestamp in `YYYY-MM-DDTHH:MM:SSZ` format
     * @type {string}
     * @memberof AdditionalInfoResponseTimestampsAvailability
     */
    from?: string;
    /**
     * A timestamp in `YYYY-MM-DDTHH:MM:SSZ` format
     * @type {string}
     * @memberof AdditionalInfoResponseTimestampsAvailability
     */
    to?: string;
}

/**
 * Check if a given object implements the AdditionalInfoResponseTimestampsAvailability interface.
 */
export function instanceOfAdditionalInfoResponseTimestampsAvailability(
    value: object
): value is AdditionalInfoResponseTimestampsAvailability {
    return true;
}

export function AdditionalInfoResponseTimestampsAvailabilityFromJSON(
    json: any
): AdditionalInfoResponseTimestampsAvailability {
    return AdditionalInfoResponseTimestampsAvailabilityFromJSONTyped(json, false);
}

export function AdditionalInfoResponseTimestampsAvailabilityFromJSONTyped(
    json: any,
    ignoreDiscriminator: boolean
): AdditionalInfoResponseTimestampsAvailability {
    if (json == null) {
        return json;
    }
    return {
        from: json["from"] == null ? undefined : json["from"],
        to: json["to"] == null ? undefined : json["to"],
    };
}

export function AdditionalInfoResponseTimestampsAvailabilityToJSON(
    json: any
): AdditionalInfoResponseTimestampsAvailability {
    return AdditionalInfoResponseTimestampsAvailabilityToJSONTyped(json, false);
}

export function AdditionalInfoResponseTimestampsAvailabilityToJSONTyped(
    value?: AdditionalInfoResponseTimestampsAvailability | null,
    ignoreDiscriminator: boolean = false
): any {
    if (value == null) {
        return value;
    }

    return {
        from: value["from"],
        to: value["to"],
    };
}
