/* tslint:disable */
/* eslint-disable */
/**
 * Trip Planner
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 10.6.21.17
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
import type { AdditionalInfoResponseInfosAffected } from "./AdditionalInfoResponseInfosAffected";
import {
    AdditionalInfoResponseInfosAffectedFromJSON,
    AdditionalInfoResponseInfosAffectedFromJSONTyped,
    AdditionalInfoResponseInfosAffectedToJSON,
    AdditionalInfoResponseInfosAffectedToJSONTyped,
} from "./AdditionalInfoResponseInfosAffected";
import type { AdditionalInfoResponseMessage } from "./AdditionalInfoResponseMessage";
import {
    AdditionalInfoResponseMessageFromJSON,
    AdditionalInfoResponseMessageFromJSONTyped,
    AdditionalInfoResponseMessageToJSON,
    AdditionalInfoResponseMessageToJSONTyped,
} from "./AdditionalInfoResponseMessage";

/**
 * Contains each of the returned service alerts.
 *
 * @export
 * @interface AdditionalInfoResponseInfos
 */
export interface AdditionalInfoResponseInfos {
    /**
     *
     * @type {AdditionalInfoResponseInfosAffected}
     * @memberof AdditionalInfoResponseInfos
     */
    affected?: AdditionalInfoResponseInfosAffected;
    /**
     * This specifies the list of current service alerts based on the specified filters.
     * @type {Array<AdditionalInfoResponseMessage>}
     * @memberof AdditionalInfoResponseInfos
     */
    current?: Array<AdditionalInfoResponseMessage>;
    /**
     * This specifies the list of previous service alerts based on the specified filters.
     * @type {Array<AdditionalInfoResponseMessage>}
     * @memberof AdditionalInfoResponseInfos
     */
    historic?: Array<AdditionalInfoResponseMessage>;
}

/**
 * Check if a given object implements the AdditionalInfoResponseInfos interface.
 */
export function instanceOfAdditionalInfoResponseInfos(
    value: object
): value is AdditionalInfoResponseInfos {
    return true;
}

export function AdditionalInfoResponseInfosFromJSON(json: any): AdditionalInfoResponseInfos {
    return AdditionalInfoResponseInfosFromJSONTyped(json, false);
}

export function AdditionalInfoResponseInfosFromJSONTyped(
    json: any,
    ignoreDiscriminator: boolean
): AdditionalInfoResponseInfos {
    if (json == null) {
        return json;
    }
    return {
        affected:
            json["affected"] == null
                ? undefined
                : AdditionalInfoResponseInfosAffectedFromJSON(json["affected"]),
        current:
            json["current"] == null
                ? undefined
                : (json["current"] as Array<any>).map(AdditionalInfoResponseMessageFromJSON),
        historic:
            json["historic"] == null
                ? undefined
                : (json["historic"] as Array<any>).map(AdditionalInfoResponseMessageFromJSON),
    };
}

export function AdditionalInfoResponseInfosToJSON(json: any): AdditionalInfoResponseInfos {
    return AdditionalInfoResponseInfosToJSONTyped(json, false);
}

export function AdditionalInfoResponseInfosToJSONTyped(
    value?: AdditionalInfoResponseInfos | null,
    ignoreDiscriminator: boolean = false
): any {
    if (value == null) {
        return value;
    }

    return {
        affected: AdditionalInfoResponseInfosAffectedToJSON(value["affected"]),
        current:
            value["current"] == null
                ? undefined
                : (value["current"] as Array<any>).map(AdditionalInfoResponseMessageToJSON),
        historic:
            value["historic"] == null
                ? undefined
                : (value["historic"] as Array<any>).map(AdditionalInfoResponseMessageToJSON),
    };
}
