/* tslint:disable */
/* eslint-disable */
/**
 * Trip Planner
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 10.6.21.17
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
import type { AdditionalInfoResponseAffectedLine } from "./AdditionalInfoResponseAffectedLine";
import {
    AdditionalInfoResponseAffectedLineFromJSON,
    AdditionalInfoResponseAffectedLineFromJSONTyped,
    AdditionalInfoResponseAffectedLineToJSON,
    AdditionalInfoResponseAffectedLineToJSONTyped,
} from "./AdditionalInfoResponseAffectedLine";
import type { AdditionalInfoResponseAffectedStop } from "./AdditionalInfoResponseAffectedStop";
import {
    AdditionalInfoResponseAffectedStopFromJSON,
    AdditionalInfoResponseAffectedStopFromJSONTyped,
    AdditionalInfoResponseAffectedStopToJSON,
    AdditionalInfoResponseAffectedStopToJSONTyped,
} from "./AdditionalInfoResponseAffectedStop";

/**
 * This specifies the list of affected stops and lines. It is an aggregate of each of the affected
 * stops and lines listed in the alerts.
 *
 * @export
 * @interface AdditionalInfoResponseInfosAffected
 */
export interface AdditionalInfoResponseInfosAffected {
    /**
     * The specifies all of the lines that are listed as affected in the alert information.
     * @type {Array<AdditionalInfoResponseAffectedLine>}
     * @memberof AdditionalInfoResponseInfosAffected
     */
    lines?: Array<AdditionalInfoResponseAffectedLine>;
    /**
     * The specifies all of the stops that are listed as affected in the alert information.
     * @type {Array<AdditionalInfoResponseAffectedStop>}
     * @memberof AdditionalInfoResponseInfosAffected
     */
    stops?: Array<AdditionalInfoResponseAffectedStop>;
}

/**
 * Check if a given object implements the AdditionalInfoResponseInfosAffected interface.
 */
export function instanceOfAdditionalInfoResponseInfosAffected(
    value: object
): value is AdditionalInfoResponseInfosAffected {
    return true;
}

export function AdditionalInfoResponseInfosAffectedFromJSON(
    json: any
): AdditionalInfoResponseInfosAffected {
    return AdditionalInfoResponseInfosAffectedFromJSONTyped(json, false);
}

export function AdditionalInfoResponseInfosAffectedFromJSONTyped(
    json: any,
    ignoreDiscriminator: boolean
): AdditionalInfoResponseInfosAffected {
    if (json == null) {
        return json;
    }
    return {
        lines:
            json["lines"] == null
                ? undefined
                : (json["lines"] as Array<any>).map(AdditionalInfoResponseAffectedLineFromJSON),
        stops:
            json["stops"] == null
                ? undefined
                : (json["stops"] as Array<any>).map(AdditionalInfoResponseAffectedStopFromJSON),
    };
}

export function AdditionalInfoResponseInfosAffectedToJSON(
    json: any
): AdditionalInfoResponseInfosAffected {
    return AdditionalInfoResponseInfosAffectedToJSONTyped(json, false);
}

export function AdditionalInfoResponseInfosAffectedToJSONTyped(
    value?: AdditionalInfoResponseInfosAffected | null,
    ignoreDiscriminator: boolean = false
): any {
    if (value == null) {
        return value;
    }

    return {
        lines:
            value["lines"] == null
                ? undefined
                : (value["lines"] as Array<any>).map(AdditionalInfoResponseAffectedLineToJSON),
        stops:
            value["stops"] == null
                ? undefined
                : (value["stops"] as Array<any>).map(AdditionalInfoResponseAffectedStopToJSON),
    };
}
