/* tslint:disable */
/* eslint-disable */
/**
 * Trip Planner
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 10.6.21.17
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
import type { AdditionalInfoResponseAffectedLine } from "./AdditionalInfoResponseAffectedLine";
import {
    AdditionalInfoResponseAffectedLineFromJSON,
    AdditionalInfoResponseAffectedLineFromJSONTyped,
    AdditionalInfoResponseAffectedLineToJSON,
    AdditionalInfoResponseAffectedLineToJSONTyped,
} from "./AdditionalInfoResponseAffectedLine";
import type { AdditionalInfoResponseAffectedStop } from "./AdditionalInfoResponseAffectedStop";
import {
    AdditionalInfoResponseAffectedStopFromJSON,
    AdditionalInfoResponseAffectedStopFromJSONTyped,
    AdditionalInfoResponseAffectedStopToJSON,
    AdditionalInfoResponseAffectedStopToJSONTyped,
} from "./AdditionalInfoResponseAffectedStop";

/**
 * This contains details about the lines and stops that are impacted by the described alert.
 *
 * @export
 * @interface AdditionalInfoResponseMessageAffected
 */
export interface AdditionalInfoResponseMessageAffected {
    /**
     * This element contains a list of lines affected by this alert.
     * @type {Array<AdditionalInfoResponseAffectedLine>}
     * @memberof AdditionalInfoResponseMessageAffected
     */
    lines?: Array<AdditionalInfoResponseAffectedLine>;
    /**
     * This element contains a list of stops affected by this alert.
     * @type {Array<AdditionalInfoResponseAffectedStop>}
     * @memberof AdditionalInfoResponseMessageAffected
     */
    stops?: Array<AdditionalInfoResponseAffectedStop>;
}

/**
 * Check if a given object implements the AdditionalInfoResponseMessageAffected interface.
 */
export function instanceOfAdditionalInfoResponseMessageAffected(
    value: object
): value is AdditionalInfoResponseMessageAffected {
    return true;
}

export function AdditionalInfoResponseMessageAffectedFromJSON(
    json: any
): AdditionalInfoResponseMessageAffected {
    return AdditionalInfoResponseMessageAffectedFromJSONTyped(json, false);
}

export function AdditionalInfoResponseMessageAffectedFromJSONTyped(
    json: any,
    ignoreDiscriminator: boolean
): AdditionalInfoResponseMessageAffected {
    if (json == null) {
        return json;
    }
    return {
        lines:
            json["lines"] == null
                ? undefined
                : (json["lines"] as Array<any>).map(AdditionalInfoResponseAffectedLineFromJSON),
        stops:
            json["stops"] == null
                ? undefined
                : (json["stops"] as Array<any>).map(AdditionalInfoResponseAffectedStopFromJSON),
    };
}

export function AdditionalInfoResponseMessageAffectedToJSON(
    json: any
): AdditionalInfoResponseMessageAffected {
    return AdditionalInfoResponseMessageAffectedToJSONTyped(json, false);
}

export function AdditionalInfoResponseMessageAffectedToJSONTyped(
    value?: AdditionalInfoResponseMessageAffected | null,
    ignoreDiscriminator: boolean = false
): any {
    if (value == null) {
        return value;
    }

    return {
        lines:
            value["lines"] == null
                ? undefined
                : (value["lines"] as Array<any>).map(AdditionalInfoResponseAffectedLineToJSON),
        stops:
            value["stops"] == null
                ? undefined
                : (value["stops"] as Array<any>).map(AdditionalInfoResponseAffectedStopToJSON),
    };
}
