/* tslint:disable */
/* eslint-disable */
/**
 * Trip Planner
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 10.6.21.17
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
/**
 * If the error was related to the API version, this element contains version information.
 *
 * @export
 * @interface ApiErrorResponseVersions
 */
export interface ApiErrorResponseVersions {
    /**
     * The version of the API handling the request
     * @type {string}
     * @memberof ApiErrorResponseVersions
     */
    controller?: string;
    /**
     * The maximum version number that can be requested in the `version` request parameter.
     * @type {string}
     * @memberof ApiErrorResponseVersions
     */
    interfaceMax?: string;
    /**
     * The minimum version number that can be requested in the `version` request parameter.
     * @type {string}
     * @memberof ApiErrorResponseVersions
     */
    interfaceMin?: string;
}

/**
 * Check if a given object implements the ApiErrorResponseVersions interface.
 */
export function instanceOfApiErrorResponseVersions(
    value: object
): value is ApiErrorResponseVersions {
    return true;
}

export function ApiErrorResponseVersionsFromJSON(json: any): ApiErrorResponseVersions {
    return ApiErrorResponseVersionsFromJSONTyped(json, false);
}

export function ApiErrorResponseVersionsFromJSONTyped(
    json: any,
    ignoreDiscriminator: boolean
): ApiErrorResponseVersions {
    if (json == null) {
        return json;
    }
    return {
        controller: json["controller"] == null ? undefined : json["controller"],
        interfaceMax: json["interfaceMax"] == null ? undefined : json["interfaceMax"],
        interfaceMin: json["interfaceMin"] == null ? undefined : json["interfaceMin"],
    };
}

export function ApiErrorResponseVersionsToJSON(json: any): ApiErrorResponseVersions {
    return ApiErrorResponseVersionsToJSONTyped(json, false);
}

export function ApiErrorResponseVersionsToJSONTyped(
    value?: ApiErrorResponseVersions | null,
    ignoreDiscriminator: boolean = false
): any {
    if (value == null) {
        return value;
    }

    return {
        controller: value["controller"],
        interfaceMax: value["interfaceMax"],
        interfaceMin: value["interfaceMin"],
    };
}
