/* tslint:disable */
/* eslint-disable */
/**
 * Trip Planner
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 10.6.21.17
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
import type { ApiErrorResponseVersions } from "./ApiErrorResponseVersions";
import {
    ApiErrorResponseVersionsFromJSON,
    ApiErrorResponseVersionsFromJSONTyped,
    ApiErrorResponseVersionsToJSON,
    ApiErrorResponseVersionsToJSONTyped,
} from "./ApiErrorResponseVersions";

/**
 * This element contains information about an error that may have occurred when handling an API request.
 *
 * @export
 * @interface ApiErrorResponse
 */
export interface ApiErrorResponse {
    /**
     * Describes the error that went wrong
     * @type {string}
     * @memberof ApiErrorResponse
     */
    message?: string;
    /**
     *
     * @type {ApiErrorResponseVersions}
     * @memberof ApiErrorResponse
     */
    versions?: ApiErrorResponseVersions;
}

/**
 * Check if a given object implements the ApiErrorResponse interface.
 */
export function instanceOfApiErrorResponse(value: object): value is ApiErrorResponse {
    return true;
}

export function ApiErrorResponseFromJSON(json: any): ApiErrorResponse {
    return ApiErrorResponseFromJSONTyped(json, false);
}

export function ApiErrorResponseFromJSONTyped(
    json: any,
    ignoreDiscriminator: boolean
): ApiErrorResponse {
    if (json == null) {
        return json;
    }
    return {
        message: json["message"] == null ? undefined : json["message"],
        versions:
            json["versions"] == null
                ? undefined
                : ApiErrorResponseVersionsFromJSON(json["versions"]),
    };
}

export function ApiErrorResponseToJSON(json: any): ApiErrorResponse {
    return ApiErrorResponseToJSONTyped(json, false);
}

export function ApiErrorResponseToJSONTyped(
    value?: ApiErrorResponse | null,
    ignoreDiscriminator: boolean = false
): any {
    if (value == null) {
        return value;
    }

    return {
        message: value["message"],
        versions: ApiErrorResponseVersionsToJSON(value["versions"]),
    };
}
