/* tslint:disable */
/* eslint-disable */
/**
 * Trip Planner
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 10.6.21.17
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
/**
 * This data contains additional information about each location, mainly related to how
 * it can be categorised or displayed on a map.
 *
 * @export
 * @interface CoordRequestResponseLocationProperties
 */
export interface CoordRequestResponseLocationProperties {
    /**
     * This value indicates how the given point can be represented on a map. For example,
     * if you have different icons for different categories, use this to determine which icon to use.
     *
     * * `CityL`
     * * `CityM`
     * * `CityS`
     * * `CityXL`
     * * `CityXS`
     * * `Generic7`
     * * `Generic8`
     * * `Generic9`
     * * `Generic20`
     * * `PoiAirportPublic`
     * * `PoiCemetry`
     * * `PoiCulture`
     * * `PoiGastro`
     * * `PoiGeneral`
     * * `PoiGovernment`
     * * `PoiHistoric`
     * * `PoiHotel`
     * * `PoiMedicine`
     * * `PoiOthers`
     * * `PoiPark`
     * * `PoiParking`
     * * `PoiPublicBuilding`
     * * `PoiReligion`
     * * `PoiSchool`
     * * `PoiSport`
     * * `PoiSwimming`
     * * `PoiTrafficSpecial`
     *
     * @type {string}
     * @memberof CoordRequestResponseLocationProperties
     */
    gISDRAWCLASS?: string;
    /**
     * This value typically either empty or `POINT`.
     * @type {string}
     * @memberof CoordRequestResponseLocationProperties
     */
    gISDRAWCLASSTYPE?: CoordRequestResponseLocationPropertiesGISDRAWCLASSTYPEEnum;
    /**
     * This data is not used at this time.
     * @type {string}
     * @memberof CoordRequestResponseLocationProperties
     */
    gISNIVEAU?: string;
    /**
     * This value indicates how the given point can be represented on a map. For example,
     * if you have different icons for different categories, use this to determine which icon to use.
     *
     * * `PoiCemetry`
     * * `PoiCulture`
     * * `PoiGastro`
     * * `PoiGeneral`
     * * `PoiGovernment`
     * * `PoiHotel`
     * * `PoiMedicine`
     * * `PoiOthers`
     * * `PoiPark`
     * * `PoiParking`
     * * `PoiPublicBuilding`
     * * `PoiReligion`
     * * `PoiSchool`
     * * `PoiSport`
     * * `PoiSwimming`
     * * `PoiTrafficSpecial`
     *
     * @type {string}
     * @memberof CoordRequestResponseLocationProperties
     */
    pOIDRAWCLASS?: string;
    /**
     * This value typically either empty or `POINT`.
     * @type {string}
     * @memberof CoordRequestResponseLocationProperties
     */
    pOIDRAWCLASSTYPE?: CoordRequestResponseLocationPropertiesPOIDRAWCLASSTYPEEnum;
    /**
     * This field contains a human-readable description of the category to which this
     * location belongs. See the description for `POI_HIERARCHY_KEY` for example values that
     * correspond to the given keys.
     *
     * @type {string}
     * @memberof CoordRequestResponseLocationProperties
     */
    pOIHIERARCHY0?: string;
    /**
     * This field contains a constant value for the category to which this category belongs.
     *
     * * `A`: Accommodation
     * * `B`: Caravan and Camping
     * * `C`: Cemetary
     * * `D`: Education
     * * `E`: Emergency or Defence
     * * `F`: Entertainment
     * * `G`: Gardens or Parklands
     * * `H`: Golf Clubs
     * * `I`: Historical or Religious
     * * `K`: Local Government
     * * `L`: Medical and Care
     * * `O`: Sporting or Recreation
     * * `Q`: Tourist Attraction
     * * `R`: Transport
     * * `S`: Utilities and Facilities
     * * `T`: Others
     *
     * @type {string}
     * @memberof CoordRequestResponseLocationProperties
     */
    pOIHIERARCHYKEY?: string;
    /**
     * This is the distance in metres to this location from the search location.
     * @type {string}
     * @memberof CoordRequestResponseLocationProperties
     */
    distance?: string;
}

/**
 * @export
 */
export const CoordRequestResponseLocationPropertiesGISDRAWCLASSTYPEEnum = {
    Point: "POINT",
} as const;
export type CoordRequestResponseLocationPropertiesGISDRAWCLASSTYPEEnum =
    (typeof CoordRequestResponseLocationPropertiesGISDRAWCLASSTYPEEnum)[keyof typeof CoordRequestResponseLocationPropertiesGISDRAWCLASSTYPEEnum];

/**
 * @export
 */
export const CoordRequestResponseLocationPropertiesPOIDRAWCLASSTYPEEnum = {
    Point: "POINT",
} as const;
export type CoordRequestResponseLocationPropertiesPOIDRAWCLASSTYPEEnum =
    (typeof CoordRequestResponseLocationPropertiesPOIDRAWCLASSTYPEEnum)[keyof typeof CoordRequestResponseLocationPropertiesPOIDRAWCLASSTYPEEnum];

/**
 * Check if a given object implements the CoordRequestResponseLocationProperties interface.
 */
export function instanceOfCoordRequestResponseLocationProperties(
    value: object
): value is CoordRequestResponseLocationProperties {
    return true;
}

export function CoordRequestResponseLocationPropertiesFromJSON(
    json: any
): CoordRequestResponseLocationProperties {
    return CoordRequestResponseLocationPropertiesFromJSONTyped(json, false);
}

export function CoordRequestResponseLocationPropertiesFromJSONTyped(
    json: any,
    ignoreDiscriminator: boolean
): CoordRequestResponseLocationProperties {
    if (json == null) {
        return json;
    }
    return {
        gISDRAWCLASS: json["GIS_DRAW_CLASS"] == null ? undefined : json["GIS_DRAW_CLASS"],
        gISDRAWCLASSTYPE:
            json["GIS_DRAW_CLASS_TYPE"] == null ? undefined : json["GIS_DRAW_CLASS_TYPE"],
        gISNIVEAU: json["GIS_NIVEAU"] == null ? undefined : json["GIS_NIVEAU"],
        pOIDRAWCLASS: json["POI_DRAW_CLASS"] == null ? undefined : json["POI_DRAW_CLASS"],
        pOIDRAWCLASSTYPE:
            json["POI_DRAW_CLASS_TYPE"] == null ? undefined : json["POI_DRAW_CLASS_TYPE"],
        pOIHIERARCHY0: json["POI_HIERARCHY_0"] == null ? undefined : json["POI_HIERARCHY_0"],
        pOIHIERARCHYKEY: json["POI_HIERARCHY_KEY"] == null ? undefined : json["POI_HIERARCHY_KEY"],
        distance: json["distance"] == null ? undefined : json["distance"],
    };
}

export function CoordRequestResponseLocationPropertiesToJSON(
    json: any
): CoordRequestResponseLocationProperties {
    return CoordRequestResponseLocationPropertiesToJSONTyped(json, false);
}

export function CoordRequestResponseLocationPropertiesToJSONTyped(
    value?: CoordRequestResponseLocationProperties | null,
    ignoreDiscriminator: boolean = false
): any {
    if (value == null) {
        return value;
    }

    return {
        GIS_DRAW_CLASS: value["gISDRAWCLASS"],
        GIS_DRAW_CLASS_TYPE: value["gISDRAWCLASSTYPE"],
        GIS_NIVEAU: value["gISNIVEAU"],
        POI_DRAW_CLASS: value["pOIDRAWCLASS"],
        POI_DRAW_CLASS_TYPE: value["pOIDRAWCLASSTYPE"],
        POI_HIERARCHY_0: value["pOIHIERARCHY0"],
        POI_HIERARCHY_KEY: value["pOIHIERARCHYKEY"],
        distance: value["distance"],
    };
}
