/* tslint:disable */
/* eslint-disable */
/**
 * Trip Planner
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 10.6.21.17
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
import type { CoordRequestResponseLocation } from "./CoordRequestResponseLocation";
import {
    CoordRequestResponseLocationFromJSON,
    CoordRequestResponseLocationFromJSONTyped,
    CoordRequestResponseLocationToJSON,
    CoordRequestResponseLocationToJSONTyped,
} from "./CoordRequestResponseLocation";
import type { ApiErrorResponse } from "./ApiErrorResponse";
import {
    ApiErrorResponseFromJSON,
    ApiErrorResponseFromJSONTyped,
    ApiErrorResponseToJSON,
    ApiErrorResponseToJSONTyped,
} from "./ApiErrorResponse";

/**
 * This is the response data returned when performing an `coord` request.
 *
 * @export
 * @interface CoordRequestResponse
 */
export interface CoordRequestResponse {
    /**
     *
     * @type {ApiErrorResponse}
     * @memberof CoordRequestResponse
     */
    error?: ApiErrorResponse;
    /**
     * This contains a list of all of the stops, reload points and places of interest found based on the given request.
     *
     * @type {Array<CoordRequestResponseLocation>}
     * @memberof CoordRequestResponse
     */
    locations?: Array<CoordRequestResponseLocation>;
    /**
     * The version of the API that provided the response. Note that if this value is different to above, then the returned data may be
     * different than expected. You can set the expected version using the `version` request parameter.
     *
     * @type {string}
     * @memberof CoordRequestResponse
     */
    version?: string;
}

/**
 * Check if a given object implements the CoordRequestResponse interface.
 */
export function instanceOfCoordRequestResponse(value: object): value is CoordRequestResponse {
    return true;
}

export function CoordRequestResponseFromJSON(json: any): CoordRequestResponse {
    return CoordRequestResponseFromJSONTyped(json, false);
}

export function CoordRequestResponseFromJSONTyped(
    json: any,
    ignoreDiscriminator: boolean
): CoordRequestResponse {
    if (json == null) {
        return json;
    }
    return {
        error: json["error"] == null ? undefined : ApiErrorResponseFromJSON(json["error"]),
        locations:
            json["locations"] == null
                ? undefined
                : (json["locations"] as Array<any>).map(CoordRequestResponseLocationFromJSON),
        version: json["version"] == null ? undefined : json["version"],
    };
}

export function CoordRequestResponseToJSON(json: any): CoordRequestResponse {
    return CoordRequestResponseToJSONTyped(json, false);
}

export function CoordRequestResponseToJSONTyped(
    value?: CoordRequestResponse | null,
    ignoreDiscriminator: boolean = false
): any {
    if (value == null) {
        return value;
    }

    return {
        error: ApiErrorResponseToJSON(value["error"]),
        locations:
            value["locations"] == null
                ? undefined
                : (value["locations"] as Array<any>).map(CoordRequestResponseLocationToJSON),
        version: value["version"],
    };
}
