/* tslint:disable */
/* eslint-disable */
/**
 * Trip Planner
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 10.6.21.17
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
import type { ParentLocation } from "./ParentLocation";
import {
    ParentLocationFromJSON,
    ParentLocationFromJSONTyped,
    ParentLocationToJSON,
    ParentLocationToJSONTyped,
} from "./ParentLocation";
import type { CoordRequestResponseLocationProperties } from "./CoordRequestResponseLocationProperties";
import {
    CoordRequestResponseLocationPropertiesFromJSON,
    CoordRequestResponseLocationPropertiesFromJSONTyped,
    CoordRequestResponseLocationPropertiesToJSON,
    CoordRequestResponseLocationPropertiesToJSONTyped,
} from "./CoordRequestResponseLocationProperties";

/**
 * Describes a single point that is returned based on the given request.
 *
 * @export
 * @interface CoordRequestResponseLocation
 */
export interface CoordRequestResponseLocation {
    /**
     * Contains exactly two values: the first value is the latitude, the second value is the longitude.
     *
     * @type {Array<number>}
     * @memberof CoordRequestResponseLocation
     */
    coord?: Array<number>;
    /**
     * This is the short version of the location name, which does not include the suburb or other information.
     *
     * @type {string}
     * @memberof CoordRequestResponseLocation
     */
    disassembledName?: string;
    /**
     * This is a unique ID for the returned location. Certain types of ID can be used for subsequent searches performed with `stop_finder`,
     * or can be used as the origin or destination in an `trip` request. The format of a location ID differs greatly, depending
     * on the type of location it is.
     *
     * @type {string}
     * @memberof CoordRequestResponseLocation
     */
    id?: string;
    /**
     * Contains a human-readable title for the location.
     *
     * @type {string}
     * @memberof CoordRequestResponseLocation
     */
    name?: string;
    /**
     *
     * @type {ParentLocation}
     * @memberof CoordRequestResponseLocation
     */
    parent?: ParentLocation;
    /**
     *
     * @type {CoordRequestResponseLocationProperties}
     * @memberof CoordRequestResponseLocation
     */
    properties?: CoordRequestResponseLocationProperties;
    /**
     * This specifies the type of the returned item. If you search with a type of `GIS_POINT`,
     * a returned item has a type of `gisPoint`.
     *
     * @type {string}
     * @memberof CoordRequestResponseLocation
     */
    type?: CoordRequestResponseLocationTypeEnum;
}

/**
 * @export
 */
export const CoordRequestResponseLocationTypeEnum = {
    Poi: "poi",
    Singlehouse: "singlehouse",
    Stop: "stop",
    Platform: "platform",
    Street: "street",
    Locality: "locality",
    Suburb: "suburb",
    GisPoint: "gisPoint",
    Unknown: "unknown",
} as const;
export type CoordRequestResponseLocationTypeEnum =
    (typeof CoordRequestResponseLocationTypeEnum)[keyof typeof CoordRequestResponseLocationTypeEnum];

/**
 * Check if a given object implements the CoordRequestResponseLocation interface.
 */
export function instanceOfCoordRequestResponseLocation(
    value: object
): value is CoordRequestResponseLocation {
    return true;
}

export function CoordRequestResponseLocationFromJSON(json: any): CoordRequestResponseLocation {
    return CoordRequestResponseLocationFromJSONTyped(json, false);
}

export function CoordRequestResponseLocationFromJSONTyped(
    json: any,
    ignoreDiscriminator: boolean
): CoordRequestResponseLocation {
    if (json == null) {
        return json;
    }
    return {
        coord: json["coord"] == null ? undefined : json["coord"],
        disassembledName: json["disassembledName"] == null ? undefined : json["disassembledName"],
        id: json["id"] == null ? undefined : json["id"],
        name: json["name"] == null ? undefined : json["name"],
        parent: json["parent"] == null ? undefined : ParentLocationFromJSON(json["parent"]),
        properties:
            json["properties"] == null
                ? undefined
                : CoordRequestResponseLocationPropertiesFromJSON(json["properties"]),
        type: json["type"] == null ? undefined : json["type"],
    };
}

export function CoordRequestResponseLocationToJSON(json: any): CoordRequestResponseLocation {
    return CoordRequestResponseLocationToJSONTyped(json, false);
}

export function CoordRequestResponseLocationToJSONTyped(
    value?: CoordRequestResponseLocation | null,
    ignoreDiscriminator: boolean = false
): any {
    if (value == null) {
        return value;
    }

    return {
        coord: value["coord"],
        disassembledName: value["disassembledName"],
        id: value["id"],
        name: value["name"],
        parent: ParentLocationToJSON(value["parent"]),
        properties: CoordRequestResponseLocationPropertiesToJSON(value["properties"]),
        type: value["type"],
    };
}
