/* tslint:disable */
/* eslint-disable */
/**
 * Trip Planner
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 10.6.21.17
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
import type { StopFinderLocation } from "./StopFinderLocation";
import {
    StopFinderLocationFromJSON,
    StopFinderLocationFromJSONTyped,
    StopFinderLocationToJSON,
    StopFinderLocationToJSONTyped,
} from "./StopFinderLocation";
import type { TripRequestResponseJourneyLegStopInfo } from "./TripRequestResponseJourneyLegStopInfo";
import {
    TripRequestResponseJourneyLegStopInfoFromJSON,
    TripRequestResponseJourneyLegStopInfoFromJSONTyped,
    TripRequestResponseJourneyLegStopInfoToJSON,
    TripRequestResponseJourneyLegStopInfoToJSONTyped,
} from "./TripRequestResponseJourneyLegStopInfo";
import type { TripTransportation } from "./TripTransportation";
import {
    TripTransportationFromJSON,
    TripTransportationFromJSONTyped,
    TripTransportationToJSON,
    TripTransportationToJSONTyped,
} from "./TripTransportation";

/**
 * Corresponds to a single departure or arrival for the given stop.
 *
 * @export
 * @interface DepartureMonitorResponseStopEvent
 */
export interface DepartureMonitorResponseStopEvent {
    /**
     * A timestamp in `YYYY-MM-DDTHH:MM:SSZ` format
     * @type {string}
     * @memberof DepartureMonitorResponseStopEvent
     */
    departureTimePlanned?: string;
    /**
     * Contains a number of service alert messages relating to this stop event.
     * Information returned here is also available using the `add_info` API endpoint.
     *
     * @type {Array<TripRequestResponseJourneyLegStopInfo>}
     * @memberof DepartureMonitorResponseStopEvent
     */
    infos?: Array<TripRequestResponseJourneyLegStopInfo>;
    /**
     *
     * @type {StopFinderLocation}
     * @memberof DepartureMonitorResponseStopEvent
     */
    location?: StopFinderLocation;
    /**
     *
     * @type {TripTransportation}
     * @memberof DepartureMonitorResponseStopEvent
     */
    transportation?: TripTransportation;
}

/**
 * Check if a given object implements the DepartureMonitorResponseStopEvent interface.
 */
export function instanceOfDepartureMonitorResponseStopEvent(
    value: object
): value is DepartureMonitorResponseStopEvent {
    return true;
}

export function DepartureMonitorResponseStopEventFromJSON(
    json: any
): DepartureMonitorResponseStopEvent {
    return DepartureMonitorResponseStopEventFromJSONTyped(json, false);
}

export function DepartureMonitorResponseStopEventFromJSONTyped(
    json: any,
    ignoreDiscriminator: boolean
): DepartureMonitorResponseStopEvent {
    if (json == null) {
        return json;
    }
    return {
        departureTimePlanned:
            json["departureTimePlanned"] == null ? undefined : json["departureTimePlanned"],
        infos:
            json["infos"] == null
                ? undefined
                : (json["infos"] as Array<any>).map(TripRequestResponseJourneyLegStopInfoFromJSON),
        location:
            json["location"] == null ? undefined : StopFinderLocationFromJSON(json["location"]),
        transportation:
            json["transportation"] == null
                ? undefined
                : TripTransportationFromJSON(json["transportation"]),
    };
}

export function DepartureMonitorResponseStopEventToJSON(
    json: any
): DepartureMonitorResponseStopEvent {
    return DepartureMonitorResponseStopEventToJSONTyped(json, false);
}

export function DepartureMonitorResponseStopEventToJSONTyped(
    value?: DepartureMonitorResponseStopEvent | null,
    ignoreDiscriminator: boolean = false
): any {
    if (value == null) {
        return value;
    }

    return {
        departureTimePlanned: value["departureTimePlanned"],
        infos:
            value["infos"] == null
                ? undefined
                : (value["infos"] as Array<any>).map(TripRequestResponseJourneyLegStopInfoToJSON),
        location: StopFinderLocationToJSON(value["location"]),
        transportation: TripTransportationToJSON(value["transportation"]),
    };
}
