/* tslint:disable */
/* eslint-disable */
/**
 * Trip Planner
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 10.6.21.17
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
import type { StopFinderLocation } from "./StopFinderLocation";
import {
    StopFinderLocationFromJSON,
    StopFinderLocationFromJSONTyped,
    StopFinderLocationToJSON,
    StopFinderLocationToJSONTyped,
} from "./StopFinderLocation";
import type { DepartureMonitorResponseStopEvent } from "./DepartureMonitorResponseStopEvent";
import {
    DepartureMonitorResponseStopEventFromJSON,
    DepartureMonitorResponseStopEventFromJSONTyped,
    DepartureMonitorResponseStopEventToJSON,
    DepartureMonitorResponseStopEventToJSONTyped,
} from "./DepartureMonitorResponseStopEvent";
import type { ApiErrorResponse } from "./ApiErrorResponse";
import {
    ApiErrorResponseFromJSON,
    ApiErrorResponseFromJSONTyped,
    ApiErrorResponseToJSON,
    ApiErrorResponseToJSONTyped,
} from "./ApiErrorResponse";

/**
 * This is the response data returned when performing an `departure_mon` request.
 *
 * @export
 * @interface DepartureMonitorResponse
 */
export interface DepartureMonitorResponse {
    /**
     *
     * @type {ApiErrorResponse}
     * @memberof DepartureMonitorResponse
     */
    error?: ApiErrorResponse;
    /**
     * Contains a list of stops that were matched based on the supplied `type_dm` and `name_dm` request values. There must be exactly
     * one location present for the `stopEvents` response data to be populated. Additionally, the `mode` request value must be set
     * to `direct`.
     *
     * @type {Array<StopFinderLocation>}
     * @memberof DepartureMonitorResponse
     */
    locations?: Array<StopFinderLocation>;
    /**
     * Contains a list of departures/arrivals for the stop included in the `location` property of the response.
     *
     * @type {Array<DepartureMonitorResponseStopEvent>}
     * @memberof DepartureMonitorResponse
     */
    stopEvents?: Array<DepartureMonitorResponseStopEvent>;
    /**
     * The version of the API that provided the response. Note that if this value is different to above, then the returned data may be
     * different than expected. You can set the expected version using the `version` request parameter.
     *
     * @type {string}
     * @memberof DepartureMonitorResponse
     */
    version?: string;
}

/**
 * Check if a given object implements the DepartureMonitorResponse interface.
 */
export function instanceOfDepartureMonitorResponse(
    value: object
): value is DepartureMonitorResponse {
    return true;
}

export function DepartureMonitorResponseFromJSON(json: any): DepartureMonitorResponse {
    return DepartureMonitorResponseFromJSONTyped(json, false);
}

export function DepartureMonitorResponseFromJSONTyped(
    json: any,
    ignoreDiscriminator: boolean
): DepartureMonitorResponse {
    if (json == null) {
        return json;
    }
    return {
        error: json["error"] == null ? undefined : ApiErrorResponseFromJSON(json["error"]),
        locations:
            json["locations"] == null
                ? undefined
                : (json["locations"] as Array<any>).map(StopFinderLocationFromJSON),
        stopEvents:
            json["stopEvents"] == null
                ? undefined
                : (json["stopEvents"] as Array<any>).map(DepartureMonitorResponseStopEventFromJSON),
        version: json["version"] == null ? undefined : json["version"],
    };
}

export function DepartureMonitorResponseToJSON(json: any): DepartureMonitorResponse {
    return DepartureMonitorResponseToJSONTyped(json, false);
}

export function DepartureMonitorResponseToJSONTyped(
    value?: DepartureMonitorResponse | null,
    ignoreDiscriminator: boolean = false
): any {
    if (value == null) {
        return value;
    }

    return {
        error: ApiErrorResponseToJSON(value["error"]),
        locations:
            value["locations"] == null
                ? undefined
                : (value["locations"] as Array<any>).map(StopFinderLocationToJSON),
        stopEvents:
            value["stopEvents"] == null
                ? undefined
                : (value["stopEvents"] as Array<any>).map(DepartureMonitorResponseStopEventToJSON),
        version: value["version"],
    };
}
