/* tslint:disable */
/* eslint-disable */
/**
 * Trip Planner
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 10.6.21.17
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
/**
 * This element contains information about a HTTP error that occurred.
 *
 * @export
 * @interface HttpErrorResponse
 */
export interface HttpErrorResponse {
    /**
     * The date and time that the error occurred.
     * @type {string}
     * @memberof HttpErrorResponse
     */
    errorDateTime?: string;
    /**
     * A detailed message about the error.
     * @type {string}
     * @memberof HttpErrorResponse
     */
    message?: string;
    /**
     * The HTTP request method used for the current request.
     * @type {string}
     * @memberof HttpErrorResponse
     */
    requestedMethod?: string;
    /**
     * The URL for the current request.
     * @type {string}
     * @memberof HttpErrorResponse
     */
    requestedUrl?: string;
    /**
     * A unique identifier for the current request.
     * @type {string}
     * @memberof HttpErrorResponse
     */
    transactionId?: string;
}

/**
 * Check if a given object implements the HttpErrorResponse interface.
 */
export function instanceOfHttpErrorResponse(value: object): value is HttpErrorResponse {
    return true;
}

export function HttpErrorResponseFromJSON(json: any): HttpErrorResponse {
    return HttpErrorResponseFromJSONTyped(json, false);
}

export function HttpErrorResponseFromJSONTyped(
    json: any,
    ignoreDiscriminator: boolean
): HttpErrorResponse {
    if (json == null) {
        return json;
    }
    return {
        errorDateTime: json["ErrorDateTime"] == null ? undefined : json["ErrorDateTime"],
        message: json["Message"] == null ? undefined : json["Message"],
        requestedMethod: json["RequestedMethod"] == null ? undefined : json["RequestedMethod"],
        requestedUrl: json["RequestedUrl"] == null ? undefined : json["RequestedUrl"],
        transactionId: json["TransactionId"] == null ? undefined : json["TransactionId"],
    };
}

export function HttpErrorResponseToJSON(json: any): HttpErrorResponse {
    return HttpErrorResponseToJSONTyped(json, false);
}

export function HttpErrorResponseToJSONTyped(
    value?: HttpErrorResponse | null,
    ignoreDiscriminator: boolean = false
): any {
    if (value == null) {
        return value;
    }

    return {
        ErrorDateTime: value["errorDateTime"],
        Message: value["message"],
        RequestedMethod: value["requestedMethod"],
        RequestedUrl: value["requestedUrl"],
        TransactionId: value["transactionId"],
    };
}
