/* tslint:disable */
/* eslint-disable */
/**
 * Trip Planner
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 10.6.21.17
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
/**
 * Describes a parent location. Locations are hierarchical, mean a location has a parent, and
 * a location may have any number of child locations. A parent location is often included with locations,
 * which can help traverse the location tree.
 *
 * @export
 * @interface ParentLocation
 */
export interface ParentLocation {
    /**
     * This is the short version of the location name, which does not include the suburb or other information.
     *
     * @type {string}
     * @memberof ParentLocation
     */
    disassembledName?: string;
    /**
     * This is a unique ID for the returned location. Certain types of ID can be used for subsequent searches performed with `stop_finder`,
     * or can be used as the origin or destination in an `trip` request. The format of a location ID differs greatly, depending
     * on the type of location it is.
     *
     * @type {string}
     * @memberof ParentLocation
     */
    id?: string;
    /**
     * This is the long version of the location name, which may include the suburb or other information.
     *
     * @type {string}
     * @memberof ParentLocation
     */
    name?: string;
    /**
     *
     * @type {ParentLocation}
     * @memberof ParentLocation
     */
    parent?: ParentLocation;
    /**
     * This is the type of location being returned. It may represent a stop or platform that a public transport service physically
     * stops at for passenger boarding, or it may represent somebody's house.
     * A value of `unknown` likely indicates bad data coming from the server. If a location is returned with this type, you can safely ignore it.
     *
     * @type {string}
     * @memberof ParentLocation
     */
    type?: ParentLocationTypeEnum;
}

/**
 * @export
 */
export const ParentLocationTypeEnum = {
    Poi: "poi",
    Singlehouse: "singlehouse",
    Stop: "stop",
    Platform: "platform",
    Street: "street",
    Locality: "locality",
    Suburb: "suburb",
    Unknown: "unknown",
} as const;
export type ParentLocationTypeEnum =
    (typeof ParentLocationTypeEnum)[keyof typeof ParentLocationTypeEnum];

/**
 * Check if a given object implements the ParentLocation interface.
 */
export function instanceOfParentLocation(value: object): value is ParentLocation {
    return true;
}

export function ParentLocationFromJSON(json: any): ParentLocation {
    return ParentLocationFromJSONTyped(json, false);
}

export function ParentLocationFromJSONTyped(
    json: any,
    ignoreDiscriminator: boolean
): ParentLocation {
    if (json == null) {
        return json;
    }
    return {
        disassembledName: json["disassembledName"] == null ? undefined : json["disassembledName"],
        id: json["id"] == null ? undefined : json["id"],
        name: json["name"] == null ? undefined : json["name"],
        parent: json["parent"] == null ? undefined : ParentLocationFromJSON(json["parent"]),
        type: json["type"] == null ? undefined : json["type"],
    };
}

export function ParentLocationToJSON(json: any): ParentLocation {
    return ParentLocationToJSONTyped(json, false);
}

export function ParentLocationToJSONTyped(
    value?: ParentLocation | null,
    ignoreDiscriminator: boolean = false
): any {
    if (value == null) {
        return value;
    }

    return {
        disassembledName: value["disassembledName"],
        id: value["id"],
        name: value["name"],
        parent: ParentLocationToJSON(value["parent"]),
        type: value["type"],
    };
}
