/* tslint:disable */
/* eslint-disable */
/**
 * Trip Planner
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 10.6.21.17
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
/**
 * This element contains additional properties about the route.
 * @export
 * @interface RouteProduct
 */
export interface RouteProduct {
    /**
     * This field indicates the type of the route, using the same values
     * as elsewhere in this API.
     *
     * * `1`: Train
     * * `2`: Metro
     * * `4`: Light Rail
     * * `5`: Bus
     * * `7`: Coach
     * * `9`: Ferry
     * * `11`: School Bus
     * * `99`: Walking
     * * `100`: Walking (Footpath)
     * * `101`: Bicycle
     * * `102`: Take Bicycle On Public Transport
     * * `103`: Kiss & Ride
     * * `104`: Park & Ride
     * * `105`: Taxi
     * * `106`: Car
     *
     * @type {number}
     * @memberof RouteProduct
     */
    _class?: number;
    /**
     * This field is used by to determine which icon to use when displaying
     * this affected route. It will typically match up with the `class` value.
     *
     * @type {number}
     * @memberof RouteProduct
     */
    iconId?: number;
    /**
     * Name of the product
     * @type {string}
     * @memberof RouteProduct
     */
    name?: string;
}

/**
 * Check if a given object implements the RouteProduct interface.
 */
export function instanceOfRouteProduct(value: object): value is RouteProduct {
    return true;
}

export function RouteProductFromJSON(json: any): RouteProduct {
    return RouteProductFromJSONTyped(json, false);
}

export function RouteProductFromJSONTyped(json: any, ignoreDiscriminator: boolean): RouteProduct {
    if (json == null) {
        return json;
    }
    return {
        _class: json["class"] == null ? undefined : json["class"],
        iconId: json["iconId"] == null ? undefined : json["iconId"],
        name: json["name"] == null ? undefined : json["name"],
    };
}

export function RouteProductToJSON(json: any): RouteProduct {
    return RouteProductToJSONTyped(json, false);
}

export function RouteProductToJSONTyped(
    value?: RouteProduct | null,
    ignoreDiscriminator: boolean = false
): any {
    if (value == null) {
        return value;
    }

    return {
        class: value["_class"],
        iconId: value["iconId"],
        name: value["name"],
    };
}
