/* tslint:disable */
/* eslint-disable */
/**
 * Trip Planner
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 10.6.21.17
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
import type { ParentLocation } from "./ParentLocation";
import {
    ParentLocationFromJSON,
    ParentLocationFromJSONTyped,
    ParentLocationToJSON,
    ParentLocationToJSONTyped,
} from "./ParentLocation";

/**
 * An assigned stop is a location that public transport stops at. Locations / places of interest that aren't stops may have one
 * or more stops "assigned" to it as being "the stop(s) you would use if you were in this location".
 *
 * @export
 * @interface StopFinderAssignedStop
 */
export interface StopFinderAssignedStop {
    /**
     * This is the mode of transport that is used to connect to this stop. The following values are available:
     *
     * * `1`: Train
     * * `2`: Metro
     * * `4`: Light Rail
     * * `5`: Bus
     * * `7`: Coach
     * * `9`: Ferry
     * * `11`: School Bus
     * * `97`: Remain On-Board
     * * `99`: Walking
     * * `100`: Walking (Footpath)
     * * `101`: Bicycle
     * * `102`: Take Bicycle On Public Transport
     * * `103`: Kiss & Ride
     * * `104`: Park & Ride
     * * `105`: Taxi
     * * `106`: Car
     *
     * @type {number}
     * @memberof StopFinderAssignedStop
     */
    connectingMode?: number;
    /**
     * Contains exactly two values: the first value is the latitude, the second value is the longitude.
     *
     * @type {Array<number>}
     * @memberof StopFinderAssignedStop
     */
    coord?: Array<number>;
    /**
     * This is the short version of the location name, which does not include the suburb or other information.
     *
     * @type {string}
     * @memberof StopFinderAssignedStop
     */
    disassembledName?: string;
    /**
     * This is the distance in metres to this stop from the location to which it is assigned.
     * @type {number}
     * @memberof StopFinderAssignedStop
     */
    distance?: number;
    /**
     * This is the number of minutes it would take to reach this stop from the location to which it is assigned.
     * @type {number}
     * @memberof StopFinderAssignedStop
     */
    duration?: number;
    /**
     * This is a unique ID for the returned location. Certain types of ID can be used for subsequent searches performed with `stop_finder`,
     * or can be used as the origin or destination in an `trip` request. The format of a location ID differs greatly, depending
     * on the type of location it is.
     *
     * @type {string}
     * @memberof StopFinderAssignedStop
     */
    id?: string;
    /**
     * This is included only if the `type` value is set to `stop`. Contains a list of modes of transport
     * that service this stop. This can be useful for showing relevant wayfinding icons when presenting users
     * with a list of matching stops to choose from.
     *
     * The following values may be present:
     *
     * * `1`: Train
     * * `2`: Metro
     * * `4`: Light Rail
     * * `5`: Bus
     * * `7`: Coach
     * * `9`: Ferry
     * * `11`: School Bus
     *
     * @type {Array<number>}
     * @memberof StopFinderAssignedStop
     */
    modes?: Array<number>;
    /**
     * This is the long version of the location name, which may include the suburb or other information.
     *
     * @type {string}
     * @memberof StopFinderAssignedStop
     */
    name?: string;
    /**
     *
     * @type {ParentLocation}
     * @memberof StopFinderAssignedStop
     */
    parent?: ParentLocation;
    /**
     * A value of `unknown` likely indicates bad data. If a location is returned with this type, you can safely ignore it.
     *
     * @type {string}
     * @memberof StopFinderAssignedStop
     */
    type?: StopFinderAssignedStopTypeEnum;
}

/**
 * @export
 */
export const StopFinderAssignedStopTypeEnum = {
    Poi: "poi",
    Singlehouse: "singlehouse",
    Stop: "stop",
    Platform: "platform",
    Street: "street",
    Locality: "locality",
    Suburb: "suburb",
    Unknown: "unknown",
} as const;
export type StopFinderAssignedStopTypeEnum =
    (typeof StopFinderAssignedStopTypeEnum)[keyof typeof StopFinderAssignedStopTypeEnum];

/**
 * Check if a given object implements the StopFinderAssignedStop interface.
 */
export function instanceOfStopFinderAssignedStop(value: object): value is StopFinderAssignedStop {
    return true;
}

export function StopFinderAssignedStopFromJSON(json: any): StopFinderAssignedStop {
    return StopFinderAssignedStopFromJSONTyped(json, false);
}

export function StopFinderAssignedStopFromJSONTyped(
    json: any,
    ignoreDiscriminator: boolean
): StopFinderAssignedStop {
    if (json == null) {
        return json;
    }
    return {
        connectingMode: json["connectingMode"] == null ? undefined : json["connectingMode"],
        coord: json["coord"] == null ? undefined : json["coord"],
        disassembledName: json["disassembledName"] == null ? undefined : json["disassembledName"],
        distance: json["distance"] == null ? undefined : json["distance"],
        duration: json["duration"] == null ? undefined : json["duration"],
        id: json["id"] == null ? undefined : json["id"],
        modes: json["modes"] == null ? undefined : json["modes"],
        name: json["name"] == null ? undefined : json["name"],
        parent: json["parent"] == null ? undefined : ParentLocationFromJSON(json["parent"]),
        type: json["type"] == null ? undefined : json["type"],
    };
}

export function StopFinderAssignedStopToJSON(json: any): StopFinderAssignedStop {
    return StopFinderAssignedStopToJSONTyped(json, false);
}

export function StopFinderAssignedStopToJSONTyped(
    value?: StopFinderAssignedStop | null,
    ignoreDiscriminator: boolean = false
): any {
    if (value == null) {
        return value;
    }

    return {
        connectingMode: value["connectingMode"],
        coord: value["coord"],
        disassembledName: value["disassembledName"],
        distance: value["distance"],
        duration: value["duration"],
        id: value["id"],
        modes: value["modes"],
        name: value["name"],
        parent: ParentLocationToJSON(value["parent"]),
        type: value["type"],
    };
}
