/* tslint:disable */
/* eslint-disable */
/**
 * Trip Planner
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 10.6.21.17
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
import type { StopFinderLocation } from "./StopFinderLocation";
import {
    StopFinderLocationFromJSON,
    StopFinderLocationFromJSONTyped,
    StopFinderLocationToJSON,
    StopFinderLocationToJSONTyped,
} from "./StopFinderLocation";
import type { ApiErrorResponse } from "./ApiErrorResponse";
import {
    ApiErrorResponseFromJSON,
    ApiErrorResponseFromJSONTyped,
    ApiErrorResponseToJSON,
    ApiErrorResponseToJSONTyped,
} from "./ApiErrorResponse";

/**
 * This element contains the response for an `stop_finder` request.
 * @export
 * @interface StopFinderResponse
 */
export interface StopFinderResponse {
    /**
     *
     * @type {ApiErrorResponse}
     * @memberof StopFinderResponse
     */
    error?: ApiErrorResponse;
    /**
     * An array of all locations that were found using the specified search input. To display the results in a way that makes sense to
     * the end user, you can sort this list by `matchQuality`. Alternatively, you can group the results by their type and/or sort them
     * alphabetically.
     *
     * @type {Array<StopFinderLocation>}
     * @memberof StopFinderResponse
     */
    locations?: Array<StopFinderLocation>;
    /**
     * The version of the API that provided the response. Note that if this value is different to above, then the returned data may be
     * different than expected. You can set the expected version using the `version` request parameter.
     *
     * @type {string}
     * @memberof StopFinderResponse
     */
    version?: string;
}

/**
 * Check if a given object implements the StopFinderResponse interface.
 */
export function instanceOfStopFinderResponse(value: object): value is StopFinderResponse {
    return true;
}

export function StopFinderResponseFromJSON(json: any): StopFinderResponse {
    return StopFinderResponseFromJSONTyped(json, false);
}

export function StopFinderResponseFromJSONTyped(
    json: any,
    ignoreDiscriminator: boolean
): StopFinderResponse {
    if (json == null) {
        return json;
    }
    return {
        error: json["error"] == null ? undefined : ApiErrorResponseFromJSON(json["error"]),
        locations:
            json["locations"] == null
                ? undefined
                : (json["locations"] as Array<any>).map(StopFinderLocationFromJSON),
        version: json["version"] == null ? undefined : json["version"],
    };
}

export function StopFinderResponseToJSON(json: any): StopFinderResponse {
    return StopFinderResponseToJSONTyped(json, false);
}

export function StopFinderResponseToJSONTyped(
    value?: StopFinderResponse | null,
    ignoreDiscriminator: boolean = false
): any {
    if (value == null) {
        return value;
    }

    return {
        error: ApiErrorResponseToJSON(value["error"]),
        locations:
            value["locations"] == null
                ? undefined
                : (value["locations"] as Array<any>).map(StopFinderLocationToJSON),
        version: value["version"],
    };
}
