/* tslint:disable */
/* eslint-disable */
/**
 * Trip Planner
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 10.6.21.17
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
import type { StopFinderAssignedStop } from "./StopFinderAssignedStop";
import {
    StopFinderAssignedStopFromJSON,
    StopFinderAssignedStopFromJSONTyped,
    StopFinderAssignedStopToJSON,
    StopFinderAssignedStopToJSONTyped,
} from "./StopFinderAssignedStop";
import type { ParentLocation } from "./ParentLocation";
import {
    ParentLocationFromJSON,
    ParentLocationFromJSONTyped,
    ParentLocationToJSON,
    ParentLocationToJSONTyped,
} from "./ParentLocation";

/**
 * This element describes a single location that is returned in an `stop_finder` request.
 * @export
 * @interface StopFinderLocation
 */
export interface StopFinderLocation {
    /**
     * This is a list of stops that are assigned to this location. This means if you're in the current location and want to catch
     * public transport, these assigned stops are directly available to you.
     *
     * @type {Array<StopFinderAssignedStop>}
     * @memberof StopFinderLocation
     */
    assignedStops?: Array<StopFinderAssignedStop>;
    /**
     * This is the number of the property, included only if the `type` value is set to `singlehouse`. Note that it is a string, as it may include non-numeric characters.
     *
     * @type {string}
     * @memberof StopFinderLocation
     */
    buildingNumber?: string;
    /**
     * Contains exactly two values: the first value is the latitude, the second value is the longitude.
     *
     * @type {Array<number>}
     * @memberof StopFinderLocation
     */
    coord?: Array<number>;
    /**
     * This is the short version of the location name, which does not include the suburb or other information.
     *
     * @type {string}
     * @memberof StopFinderLocation
     */
    disassembledName?: string;
    /**
     * This is a unique ID for the returned location. Certain types of ID can be used for subsequent searches performed with `stop_finder`,
     * or can be used as the origin or destination in an `trip` request. The format of a location ID differs greatly, depending
     * on the type of location it is.
     *
     * @type {string}
     * @memberof StopFinderLocation
     */
    id?: string;
    /**
     * Indicates whether or not this is the best match out of all the returned locations.
     * @type {boolean}
     * @memberof StopFinderLocation
     */
    isBest?: boolean;
    /**
     * This determines whether the id property is a global stop id or not
     *
     * @type {boolean}
     * @memberof StopFinderLocation
     */
    isGlobalId?: boolean;
    /**
     * This value indicates how well the returned stop matches the search query. A higher number indicates a better match.
     * @type {number}
     * @memberof StopFinderLocation
     */
    matchQuality?: number;
    /**
     * This is included only if the `type` value is set to `stop`. Contains a list of modes of transport
     * that service this stop. This can be useful for showing relevant wayfinding icons when presenting users
     * with a list of matching stops to choose from.
     *
     * The following values may be present:
     *
     * * `1`: Train
     * * `2`: Metro
     * * `4`: Light Rail
     * * `5`: Bus
     * * `7`: Coach
     * * `9`: Ferry
     * * `11`: School Bus
     *
     * @type {Array<number>}
     * @memberof StopFinderLocation
     */
    modes?: Array<number>;
    /**
     * This is the long version of the location name, which may include the suburb or other information.
     *
     * @type {string}
     * @memberof StopFinderLocation
     */
    name?: string;
    /**
     *
     * @type {ParentLocation}
     * @memberof StopFinderLocation
     */
    parent?: ParentLocation;
    /**
     * This is included only if the `type` value is set to `street` or `singlehouse`.
     * @type {string}
     * @memberof StopFinderLocation
     */
    streetName?: string;
    /**
     * This is the type of location being returned. It may represent a stop or platform that a public transport service physically
     * stops at for passenger boarding, or it may represent somebody's house.
     * A value of `unknown` likely indicates bad data coming from the server. If a location is returned with this type, you can safely ignore it.
     *
     * @type {string}
     * @memberof StopFinderLocation
     */
    type?: StopFinderLocationTypeEnum;
}

/**
 * @export
 */
export const StopFinderLocationTypeEnum = {
    Poi: "poi",
    Singlehouse: "singlehouse",
    Stop: "stop",
    Platform: "platform",
    Street: "street",
    Locality: "locality",
    Suburb: "suburb",
    Address: "address",
    Unknown: "unknown",
} as const;
export type StopFinderLocationTypeEnum =
    (typeof StopFinderLocationTypeEnum)[keyof typeof StopFinderLocationTypeEnum];

/**
 * Check if a given object implements the StopFinderLocation interface.
 */
export function instanceOfStopFinderLocation(value: object): value is StopFinderLocation {
    return true;
}

export function StopFinderLocationFromJSON(json: any): StopFinderLocation {
    return StopFinderLocationFromJSONTyped(json, false);
}

export function StopFinderLocationFromJSONTyped(
    json: any,
    ignoreDiscriminator: boolean
): StopFinderLocation {
    if (json == null) {
        return json;
    }
    return {
        assignedStops:
            json["assignedStops"] == null
                ? undefined
                : (json["assignedStops"] as Array<any>).map(StopFinderAssignedStopFromJSON),
        buildingNumber: json["buildingNumber"] == null ? undefined : json["buildingNumber"],
        coord: json["coord"] == null ? undefined : json["coord"],
        disassembledName: json["disassembledName"] == null ? undefined : json["disassembledName"],
        id: json["id"] == null ? undefined : json["id"],
        isBest: json["isBest"] == null ? undefined : json["isBest"],
        isGlobalId: json["isGlobalId"] == null ? undefined : json["isGlobalId"],
        matchQuality: json["matchQuality"] == null ? undefined : json["matchQuality"],
        modes: json["modes"] == null ? undefined : json["modes"],
        name: json["name"] == null ? undefined : json["name"],
        parent: json["parent"] == null ? undefined : ParentLocationFromJSON(json["parent"]),
        streetName: json["streetName"] == null ? undefined : json["streetName"],
        type: json["type"] == null ? undefined : json["type"],
    };
}

export function StopFinderLocationToJSON(json: any): StopFinderLocation {
    return StopFinderLocationToJSONTyped(json, false);
}

export function StopFinderLocationToJSONTyped(
    value?: StopFinderLocation | null,
    ignoreDiscriminator: boolean = false
): any {
    if (value == null) {
        return value;
    }

    return {
        assignedStops:
            value["assignedStops"] == null
                ? undefined
                : (value["assignedStops"] as Array<any>).map(StopFinderAssignedStopToJSON),
        buildingNumber: value["buildingNumber"],
        coord: value["coord"],
        disassembledName: value["disassembledName"],
        id: value["id"],
        isBest: value["isBest"],
        isGlobalId: value["isGlobalId"],
        matchQuality: value["matchQuality"],
        modes: value["modes"],
        name: value["name"],
        parent: ParentLocationToJSON(value["parent"]),
        streetName: value["streetName"],
        type: value["type"],
    };
}
