/* tslint:disable */
/* eslint-disable */
/**
 * Trip Planner
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 10.6.21.17
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
import type { TripRequestResponseJourneyLegStopProperties } from "./TripRequestResponseJourneyLegStopProperties";
import {
    TripRequestResponseJourneyLegStopPropertiesFromJSON,
    TripRequestResponseJourneyLegStopPropertiesFromJSONTyped,
    TripRequestResponseJourneyLegStopPropertiesToJSON,
    TripRequestResponseJourneyLegStopPropertiesToJSONTyped,
} from "./TripRequestResponseJourneyLegStopProperties";
import type { ParentLocation } from "./ParentLocation";
import {
    ParentLocationFromJSON,
    ParentLocationFromJSONTyped,
    ParentLocationToJSON,
    ParentLocationToJSONTyped,
} from "./ParentLocation";

/**
 * Contains information about a single stop in the journey leg.
 * Typically, the first stop in a journey leg will only include departure time information,
 * while the last stop in a journey leg will only include arrival time information. Stops in between
 * will include both arrival and departure time information.
 *
 * @export
 * @interface TripRequestResponseJourneyLegStop
 */
export interface TripRequestResponseJourneyLegStop {
    /**
     * A timestamp in `YYYY-MM-DDTHH:MM:SSZ` format that indicates the estimated arrival time. If real-time
     * information is available then this timestamp is the real-time estimate, otherwise it is the same as the
     * value in `arrivalTimePlanned`.
     *
     * @type {string}
     * @memberof TripRequestResponseJourneyLegStop
     */
    arrivalTimeEstimated?: string;
    /**
     * A timestamp in `YYYY-MM-DDTHH:MM:SSZ` format that indicates the planned arrival time. This is
     * the original scheduled time.
     *
     * @type {string}
     * @memberof TripRequestResponseJourneyLegStop
     */
    arrivalTimePlanned?: string;
    /**
     * Contains exactly two values: the first value is the latitude, the second value is the longitude.
     *
     * @type {Array<number>}
     * @memberof TripRequestResponseJourneyLegStop
     */
    coord?: Array<number>;
    /**
     * A timestamp in `YYYY-MM-DDTHH:MM:SSZ` format that indicates the estimated departure time. If real-time
     * information is available then this timestamp is the real-time estimate, otherwise it is the same as the
     * value in `departureTimePlanned`.
     *
     * @type {string}
     * @memberof TripRequestResponseJourneyLegStop
     */
    departureTimeEstimated?: string;
    /**
     * A timestamp in `YYYY-MM-DDTHH:MM:SSZ` format that indicates the planned departure time. This is
     * the original scheduled time.
     *
     * @type {string}
     * @memberof TripRequestResponseJourneyLegStop
     */
    departureTimePlanned?: string;
    /**
     * This is the short version of the location name, which does not include the suburb or other information.
     *
     * @type {string}
     * @memberof TripRequestResponseJourneyLegStop
     */
    disassembledName?: string;
    /**
     * This is a unique ID for the returned location. Certain types of ID can be used for subsequent searches performed with `stop_finder`,
     * or can be used as the origin or destination in an `trip` request. The format of a location ID differs greatly, depending
     * on the type of location it is.
     *
     * @type {string}
     * @memberof TripRequestResponseJourneyLegStop
     */
    id?: string;
    /**
     * This is the long version of the location name, which may include the suburb or other information.
     *
     * @type {string}
     * @memberof TripRequestResponseJourneyLegStop
     */
    name?: string;
    /**
     *
     * @type {ParentLocation}
     * @memberof TripRequestResponseJourneyLegStop
     */
    parent?: ParentLocation;
    /**
     *
     * @type {TripRequestResponseJourneyLegStopProperties}
     * @memberof TripRequestResponseJourneyLegStop
     */
    properties?: TripRequestResponseJourneyLegStopProperties;
    /**
     * This is the type of location being returned. It will typically represent a specific stop or platform.
     *
     * @type {string}
     * @memberof TripRequestResponseJourneyLegStop
     */
    type?: TripRequestResponseJourneyLegStopTypeEnum;
}

/**
 * @export
 */
export const TripRequestResponseJourneyLegStopTypeEnum = {
    Poi: "poi",
    Singlehouse: "singlehouse",
    Stop: "stop",
    Platform: "platform",
    Street: "street",
    Locality: "locality",
    Suburb: "suburb",
    Unknown: "unknown",
} as const;
export type TripRequestResponseJourneyLegStopTypeEnum =
    (typeof TripRequestResponseJourneyLegStopTypeEnum)[keyof typeof TripRequestResponseJourneyLegStopTypeEnum];

/**
 * Check if a given object implements the TripRequestResponseJourneyLegStop interface.
 */
export function instanceOfTripRequestResponseJourneyLegStop(
    value: object
): value is TripRequestResponseJourneyLegStop {
    return true;
}

export function TripRequestResponseJourneyLegStopFromJSON(
    json: any
): TripRequestResponseJourneyLegStop {
    return TripRequestResponseJourneyLegStopFromJSONTyped(json, false);
}

export function TripRequestResponseJourneyLegStopFromJSONTyped(
    json: any,
    ignoreDiscriminator: boolean
): TripRequestResponseJourneyLegStop {
    if (json == null) {
        return json;
    }
    return {
        arrivalTimeEstimated:
            json["arrivalTimeEstimated"] == null ? undefined : json["arrivalTimeEstimated"],
        arrivalTimePlanned:
            json["arrivalTimePlanned"] == null ? undefined : json["arrivalTimePlanned"],
        coord: json["coord"] == null ? undefined : json["coord"],
        departureTimeEstimated:
            json["departureTimeEstimated"] == null ? undefined : json["departureTimeEstimated"],
        departureTimePlanned:
            json["departureTimePlanned"] == null ? undefined : json["departureTimePlanned"],
        disassembledName: json["disassembledName"] == null ? undefined : json["disassembledName"],
        id: json["id"] == null ? undefined : json["id"],
        name: json["name"] == null ? undefined : json["name"],
        parent: json["parent"] == null ? undefined : ParentLocationFromJSON(json["parent"]),
        properties:
            json["properties"] == null
                ? undefined
                : TripRequestResponseJourneyLegStopPropertiesFromJSON(json["properties"]),
        type: json["type"] == null ? undefined : json["type"],
    };
}

export function TripRequestResponseJourneyLegStopToJSON(
    json: any
): TripRequestResponseJourneyLegStop {
    return TripRequestResponseJourneyLegStopToJSONTyped(json, false);
}

export function TripRequestResponseJourneyLegStopToJSONTyped(
    value?: TripRequestResponseJourneyLegStop | null,
    ignoreDiscriminator: boolean = false
): any {
    if (value == null) {
        return value;
    }

    return {
        arrivalTimeEstimated: value["arrivalTimeEstimated"],
        arrivalTimePlanned: value["arrivalTimePlanned"],
        coord: value["coord"],
        departureTimeEstimated: value["departureTimeEstimated"],
        departureTimePlanned: value["departureTimePlanned"],
        disassembledName: value["disassembledName"],
        id: value["id"],
        name: value["name"],
        parent: ParentLocationToJSON(value["parent"]),
        properties: TripRequestResponseJourneyLegStopPropertiesToJSON(value["properties"]),
        type: value["type"],
    };
}
