/* tslint:disable */
/* eslint-disable */
/**
 * Trip Planner
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 10.6.21.17
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
/**
 * Describes a single download available for this journey stop.
 * @export
 * @interface TripRequestResponseJourneyLegStopDownload
 */
export interface TripRequestResponseJourneyLegStopDownload {
    /**
     * This indicates what type of download this is. For example, `RM` refers to Route Map.
     *
     * @type {string}
     * @memberof TripRequestResponseJourneyLegStopDownload
     */
    type?: string;
    /**
     * This is the URL for the download.
     *
     * @type {string}
     * @memberof TripRequestResponseJourneyLegStopDownload
     */
    url?: string;
}

/**
 * Check if a given object implements the TripRequestResponseJourneyLegStopDownload interface.
 */
export function instanceOfTripRequestResponseJourneyLegStopDownload(
    value: object
): value is TripRequestResponseJourneyLegStopDownload {
    return true;
}

export function TripRequestResponseJourneyLegStopDownloadFromJSON(
    json: any
): TripRequestResponseJourneyLegStopDownload {
    return TripRequestResponseJourneyLegStopDownloadFromJSONTyped(json, false);
}

export function TripRequestResponseJourneyLegStopDownloadFromJSONTyped(
    json: any,
    ignoreDiscriminator: boolean
): TripRequestResponseJourneyLegStopDownload {
    if (json == null) {
        return json;
    }
    return {
        type: json["type"] == null ? undefined : json["type"],
        url: json["url"] == null ? undefined : json["url"],
    };
}

export function TripRequestResponseJourneyLegStopDownloadToJSON(
    json: any
): TripRequestResponseJourneyLegStopDownload {
    return TripRequestResponseJourneyLegStopDownloadToJSONTyped(json, false);
}

export function TripRequestResponseJourneyLegStopDownloadToJSONTyped(
    value?: TripRequestResponseJourneyLegStopDownload | null,
    ignoreDiscriminator: boolean = false
): any {
    if (value == null) {
        return value;
    }

    return {
        type: value["type"],
        url: value["url"],
    };
}
