/* tslint:disable */
/* eslint-disable */
/**
 * Trip Planner
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 10.6.21.17
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
/**
 * This element describes the operator of this route.
 *
 * @export
 * @interface TripTransportationOperator
 */
export interface TripTransportationOperator {
    /**
     * Contains a unique identifier for the given operator.
     *
     * @type {string}
     * @memberof TripTransportationOperator
     */
    id?: string;
    /**
     * Contains the name of the operator of the route.
     *
     * @type {string}
     * @memberof TripTransportationOperator
     */
    name?: string;
}

/**
 * Check if a given object implements the TripTransportationOperator interface.
 */
export function instanceOfTripTransportationOperator(
    value: object
): value is TripTransportationOperator {
    return true;
}

export function TripTransportationOperatorFromJSON(json: any): TripTransportationOperator {
    return TripTransportationOperatorFromJSONTyped(json, false);
}

export function TripTransportationOperatorFromJSONTyped(
    json: any,
    ignoreDiscriminator: boolean
): TripTransportationOperator {
    if (json == null) {
        return json;
    }
    return {
        id: json["id"] == null ? undefined : json["id"],
        name: json["name"] == null ? undefined : json["name"],
    };
}

export function TripTransportationOperatorToJSON(json: any): TripTransportationOperator {
    return TripTransportationOperatorToJSONTyped(json, false);
}

export function TripTransportationOperatorToJSONTyped(
    value?: TripTransportationOperator | null,
    ignoreDiscriminator: boolean = false
): any {
    if (value == null) {
        return value;
    }

    return {
        id: value["id"],
        name: value["name"],
    };
}
