/* tslint:disable */
/* eslint-disable */
/**
 * Trip Planner
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 10.6.21.17
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
/**
 * This element describes a single message that may be included with an `trip` request.
 * @export
 * @interface TripRequestResponseMessage
 */
export interface TripRequestResponseMessage {
    /**
     * This is an error/warning code for the message. Note that the same code may be returned
     * with a different meaning, depending on the context. The following error codes are possible:
     *
     * * `-1000` (`PLACE_INVALID`) - Invalid locality input
     * * `-1001` (`PLACE_WITHOUT_STOPS`) - Verified locality does not have stops
     * * `-1010` (`PLACE_UNKNOWN_POOL`) - Locality not in locality tree
     * * `-1020` (`PLACE_ALPHA_INVALID`) - Invalid alpha list
     *
     * * `-2000` (`STOP_INVALID`) - Invalid stop input
     * * `-2001` (`STOP_PLACE_ID_INVALID`) - Stop number not in locality
     *
     * * `-3000` (`ADDRESS_INVALID`) - Invalid address input
     * * `-3001` (`ADDRESS_PLACE_WITHOUT_ADDR`) - Locality does not have any addresses
     *
     * * `-1000` (`IT_COORD_UNKNOWN`) - Transferred coordinate not supported (incorrect coordinate system)
     * * `-1001` (`IT_COORD_OUT_OF_REGION`) - Transferred coordinates not supported (outside of region)
     * * `-1002` (`IT_COORD_FORMAT_UNKNOWN`) - Transferred coordinate is ok, but the format does not match the value
     * * `-200` (`IT_GEOREF_UNKNOWN`) - Invalid georeference
     * * `-201` (`IT_GEOREF_OUT_OF_REGION`) - Invalid georeference section < 0 or > length of route section
     * * `-300` (`IT_NO_START`) - No origin entered
     * * `-301` (`IT_NO_DESTINATION`) - No destination entered
     * * `-302` (`IT_NO_CONNECTION`) - No journey found
     * * `-303` (`IT_NO_TRANSITIONS`) - No transition point
     *
     * * `-3000` (`IT_ADDRESS_INVALID`) - Address invalid
     * * `-3001` (`IT_ADDRESS_PLACE_WITHOUT_ADDR`) - Locality does not have any addresses
     * * `-3002` (`IT_ADDRESS_EMPTY`) - Empty address input
     *
     * * `-5000` (`IT_LOCATOR_INVALID`) - Input locality is invalid
     * * `-5001` (`IT_LOCATOR_INVALID_POOL`) - Input locality not available in locality tree
     * * `-5002` (`IT_LOCATOR_BULK_POSTCODE`) - Bulk postcode, postcode with addresses
     *
     * * `-4000` (`IT_STREET_INVALID`) - Input street is invalid
     * * `-4001` (`IT_STREE_PLACE_WITHOUT_ADDR`) - Locality does not have any streets
     *
     * * `-8010` (`ANY_UNIQUE`) - Any input uniquely verified
     * * `-8011` (`ANY_LIST`) - Any list verified
     * * `-8012` (`ANY_INVALID`) - Any input invalid
     * * `-8013` (`ANY_PLACE_WITHOUT_MATCHES`) - Any location found, but cannot be verified
     * * `-8014` (`ANY_TOO_MANY_MATCHES`) - Any input has too many matches
     * * `-8020` (`ANY_MATCH_NONE`) - No matches
     * * `-8031` (`ANY_MATCH`) - Matches (e.g. buildings) found for a street
     * * `-8032` (`ANY_NO_MATCH`) - No matches found (e.g. buildings) for a street
     *
     * * `-4000` (`NO_CONNECTION`) - No journey found for the time entered
     * * `-4001` (`DATE_INVALID`) - Date not possible in the current timetable period
     * * `-4002` (`NO_ORIGIN`) - No origin verified
     * * `-4003` (`NO_DESTINATION`) - No destination verified
     * * `-4004` (`ORIGIN_UNKNOWN`) - Origin exists, but cannot be identified
     * * `-4005` (`DESTINATION_UNKNOWN`) - Destination exists, but cannot be identified
     * * `-4006` (`JUST_WALK`) - Only a walk has been found
     * * `-4007` (`ORIGIN_EQUI_DEST`) - Origin and destination are identical
     * * `-4008` (`VIA_UNKNOWN`) - Unknown via-point
     * * `-4009` (`TIMESPAN_INVALID`) - Time interval is invalid
     * * `-4010` (`VIA_NOINTERCHANGE`) - Via stop point is not an interchange stop
     * * `-4011` (`VIA_INVALID`) - Invalid via input
     * * `+4011` (`TRIPSTATUS_ALREADYFOUND`) - Moved journey already exists
     * * `-4012` (`ORIGIN_OUTOFPERMITTEDAREA`) - Origin outside the valid zone (e.g. fare zone)
     * * `-4013` (`DESTINATION_OUTOFPERMITTEDAREA`) - Destination outside the valid zone (e.g. fare zone)
     * * `-4014` (`VIA_OUTOFPERMITTEDAREA`) - Via outside the valid zone (e.g. fare zone)
     * * `-4020` (`NO_TRANSITION`) - No transition point found
     * * `-4030` (`NO_DEPARTURE`) - No departures found
     * * `-4040` (`NO_ARRIVAL`) - No arrivals found
     * * `-4050` (`NO_SERVINGLINES`) - No services found at this stop
     * * `-4060` (`NO_MATCHINGOPERATORS`) - No matching operators
     *
     * * `-4100` (`NO_CONNECTION_BECAUSE_OF_RULE`) - No journey because of a rule
     * * `-4101` (`RULE_CHANGED_OPTIONS`) - Rule changed the options
     * * `-4102` (`RULE_CHANGED_USEONLY`) - Rule chagned the permitted vehicles
     * * `-4103` (`RECOMPUTE_BECAUSE_OF_RULE`) - Journey has been recalculated due to a rule with different parameters
     * * `-4104` (`RULE_CHANGED_WITHOUTVIA`) - Rule removed the via point
     * * `-4300` (`NO_CONNECTION_BECAUSE_OF_PREFERTOEXCLUDE_SETTINGS`) - Invalid prefer-to-exclude parameter
     * * `-4301` (`NO_CONNECTION_BECAUSE_OF_PREFERTOINCLUDE_SETTINGS`) - Invalid prefer-to-include parameter
     * * `-4302` (`NO_CONNECTION_BECAUSE_OF_MIXEDSETTING_SETTINGS`) - Invalid mixing of prefer-to-exclude/include parameters
     * * `-4303` (`NO_CONNECTION_BECAUSE_OF_WALKING_SETTINGS`) - Invalid footpath parameter
     * * `-9999` (`TRIP_CANCELLED`) - Trip has been cancelled
     * * `-10015` (`ERROR_ITROUTER_NO_IT_CONN`) - No journey found
     *
     * @type {number}
     * @memberof TripRequestResponseMessage
     */
    code?: number;
    /**
     * This is the error summary for the given message.
     * @type {string}
     * @memberof TripRequestResponseMessage
     */
    error?: string;
    /**
     * Indicates the server module that provided this system message.
     * @type {string}
     * @memberof TripRequestResponseMessage
     */
    module?: string;
    /**
     * Indicates the type of system message.
     * @type {string}
     * @memberof TripRequestResponseMessage
     */
    type?: string;
}

/**
 * Check if a given object implements the TripRequestResponseMessage interface.
 */
export function instanceOfTripRequestResponseMessage(
    value: object
): value is TripRequestResponseMessage {
    return true;
}

export function TripRequestResponseMessageFromJSON(json: any): TripRequestResponseMessage {
    return TripRequestResponseMessageFromJSONTyped(json, false);
}

export function TripRequestResponseMessageFromJSONTyped(
    json: any,
    ignoreDiscriminator: boolean
): TripRequestResponseMessage {
    if (json == null) {
        return json;
    }
    return {
        code: json["code"] == null ? undefined : json["code"],
        error: json["error"] == null ? undefined : json["error"],
        module: json["module"] == null ? undefined : json["module"],
        type: json["type"] == null ? undefined : json["type"],
    };
}

export function TripRequestResponseMessageToJSON(json: any): TripRequestResponseMessage {
    return TripRequestResponseMessageToJSONTyped(json, false);
}

export function TripRequestResponseMessageToJSONTyped(
    value?: TripRequestResponseMessage | null,
    ignoreDiscriminator: boolean = false
): any {
    if (value == null) {
        return value;
    }

    return {
        code: value["code"],
        error: value["error"],
        module: value["module"],
        type: value["type"],
    };
}
