/* tslint:disable */
/* eslint-disable */
/**
 * Trip Planner
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 10.6.21.17
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
import type { TripRequestResponseJourneyLegStopFootpathInfoFootpathElem } from "./TripRequestResponseJourneyLegStopFootpathInfoFootpathElem";
import {
    TripRequestResponseJourneyLegStopFootpathInfoFootpathElemFromJSON,
    TripRequestResponseJourneyLegStopFootpathInfoFootpathElemFromJSONTyped,
    TripRequestResponseJourneyLegStopFootpathInfoFootpathElemToJSON,
    TripRequestResponseJourneyLegStopFootpathInfoFootpathElemToJSONTyped,
} from "./TripRequestResponseJourneyLegStopFootpathInfoFootpathElem";

/**
 * Contains walking directions for a walking leg.
 * @export
 * @interface TripRequestResponseJourneyLegStopFootpathInfo
 */
export interface TripRequestResponseJourneyLegStopFootpathInfo {
    /**
     * This is approximately how long in seconds the walking instructions contained in this element take to perform.
     *
     * @type {number}
     * @memberof TripRequestResponseJourneyLegStopFootpathInfo
     */
    duration?: number;
    /**
     * This describes the specific instructions for the walking leg.
     *
     * @type {Array<TripRequestResponseJourneyLegStopFootpathInfoFootpathElem>}
     * @memberof TripRequestResponseJourneyLegStopFootpathInfo
     */
    footPathElem?: Array<TripRequestResponseJourneyLegStopFootpathInfoFootpathElem>;
    /**
     * This indicates where in the leg the walking part of this legs occurs, since for some legs this
     * is included with transportation on a vehicle.
     *
     * @type {string}
     * @memberof TripRequestResponseJourneyLegStopFootpathInfo
     */
    position?: TripRequestResponseJourneyLegStopFootpathInfoPositionEnum;
}

/**
 * @export
 */
export const TripRequestResponseJourneyLegStopFootpathInfoPositionEnum = {
    Before: "BEFORE",
    After: "AFTER",
    Idest: "IDEST",
} as const;
export type TripRequestResponseJourneyLegStopFootpathInfoPositionEnum =
    (typeof TripRequestResponseJourneyLegStopFootpathInfoPositionEnum)[keyof typeof TripRequestResponseJourneyLegStopFootpathInfoPositionEnum];

/**
 * Check if a given object implements the TripRequestResponseJourneyLegStopFootpathInfo interface.
 */
export function instanceOfTripRequestResponseJourneyLegStopFootpathInfo(
    value: object
): value is TripRequestResponseJourneyLegStopFootpathInfo {
    return true;
}

export function TripRequestResponseJourneyLegStopFootpathInfoFromJSON(
    json: any
): TripRequestResponseJourneyLegStopFootpathInfo {
    return TripRequestResponseJourneyLegStopFootpathInfoFromJSONTyped(json, false);
}

export function TripRequestResponseJourneyLegStopFootpathInfoFromJSONTyped(
    json: any,
    ignoreDiscriminator: boolean
): TripRequestResponseJourneyLegStopFootpathInfo {
    if (json == null) {
        return json;
    }
    return {
        duration: json["duration"] == null ? undefined : json["duration"],
        footPathElem:
            json["footPathElem"] == null
                ? undefined
                : (json["footPathElem"] as Array<any>).map(
                      TripRequestResponseJourneyLegStopFootpathInfoFootpathElemFromJSON
                  ),
        position: json["position"] == null ? undefined : json["position"],
    };
}

export function TripRequestResponseJourneyLegStopFootpathInfoToJSON(
    json: any
): TripRequestResponseJourneyLegStopFootpathInfo {
    return TripRequestResponseJourneyLegStopFootpathInfoToJSONTyped(json, false);
}

export function TripRequestResponseJourneyLegStopFootpathInfoToJSONTyped(
    value?: TripRequestResponseJourneyLegStopFootpathInfo | null,
    ignoreDiscriminator: boolean = false
): any {
    if (value == null) {
        return value;
    }

    return {
        duration: value["duration"],
        footPathElem:
            value["footPathElem"] == null
                ? undefined
                : (value["footPathElem"] as Array<any>).map(
                      TripRequestResponseJourneyLegStopFootpathInfoFootpathElemToJSON
                  ),
        position: value["position"],
    };
}
