/* tslint:disable */
/* eslint-disable */
/**
 * Trip Planner
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 10.6.21.17
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
import type { TripRequestResponseJourneyLegPathDescription } from "./TripRequestResponseJourneyLegPathDescription";
import {
    TripRequestResponseJourneyLegPathDescriptionFromJSON,
    TripRequestResponseJourneyLegPathDescriptionFromJSONTyped,
    TripRequestResponseJourneyLegPathDescriptionToJSON,
    TripRequestResponseJourneyLegPathDescriptionToJSONTyped,
} from "./TripRequestResponseJourneyLegPathDescription";
import type { TripRequestResponseJourneyLegStop } from "./TripRequestResponseJourneyLegStop";
import {
    TripRequestResponseJourneyLegStopFromJSON,
    TripRequestResponseJourneyLegStopFromJSONTyped,
    TripRequestResponseJourneyLegStopToJSON,
    TripRequestResponseJourneyLegStopToJSONTyped,
} from "./TripRequestResponseJourneyLegStop";
import type { TripRequestResponseJourneyLegProperties } from "./TripRequestResponseJourneyLegProperties";
import {
    TripRequestResponseJourneyLegPropertiesFromJSON,
    TripRequestResponseJourneyLegPropertiesFromJSONTyped,
    TripRequestResponseJourneyLegPropertiesToJSON,
    TripRequestResponseJourneyLegPropertiesToJSONTyped,
} from "./TripRequestResponseJourneyLegProperties";
import type { TripRequestResponseJourneyLegInterchange } from "./TripRequestResponseJourneyLegInterchange";
import {
    TripRequestResponseJourneyLegInterchangeFromJSON,
    TripRequestResponseJourneyLegInterchangeFromJSONTyped,
    TripRequestResponseJourneyLegInterchangeToJSON,
    TripRequestResponseJourneyLegInterchangeToJSONTyped,
} from "./TripRequestResponseJourneyLegInterchange";
import type { TripRequestResponseJourneyLegStopFootpathInfo } from "./TripRequestResponseJourneyLegStopFootpathInfo";
import {
    TripRequestResponseJourneyLegStopFootpathInfoFromJSON,
    TripRequestResponseJourneyLegStopFootpathInfoFromJSONTyped,
    TripRequestResponseJourneyLegStopFootpathInfoToJSON,
    TripRequestResponseJourneyLegStopFootpathInfoToJSONTyped,
} from "./TripRequestResponseJourneyLegStopFootpathInfo";
import type { TripRequestResponseJourneyLegHintsInner } from "./TripRequestResponseJourneyLegHintsInner";
import {
    TripRequestResponseJourneyLegHintsInnerFromJSON,
    TripRequestResponseJourneyLegHintsInnerFromJSONTyped,
    TripRequestResponseJourneyLegHintsInnerToJSON,
    TripRequestResponseJourneyLegHintsInnerToJSONTyped,
} from "./TripRequestResponseJourneyLegHintsInner";
import type { TripRequestResponseJourneyLegStopInfo } from "./TripRequestResponseJourneyLegStopInfo";
import {
    TripRequestResponseJourneyLegStopInfoFromJSON,
    TripRequestResponseJourneyLegStopInfoFromJSONTyped,
    TripRequestResponseJourneyLegStopInfoToJSON,
    TripRequestResponseJourneyLegStopInfoToJSONTyped,
} from "./TripRequestResponseJourneyLegStopInfo";
import type { TripTransportation } from "./TripTransportation";
import {
    TripTransportationFromJSON,
    TripTransportationFromJSONTyped,
    TripTransportationToJSON,
    TripTransportationToJSONTyped,
} from "./TripTransportation";

/**
 * This element describes a single leg of a journey. A journey is made up of one or more legs.
 * @export
 * @interface TripRequestResponseJourneyLeg
 */
export interface TripRequestResponseJourneyLeg {
    /**
     * This elements contains a list of coordinates that this journey leg follows. A line between
     * can be plotted between these coordinates in order when representing the journey on a map
     * in order to show where the vehicle travels (or for a walking leg, the path to be walked).
     *
     * @type {Array<Array<number>>}
     * @memberof TripRequestResponseJourneyLeg
     */
    coords?: Array<Array<number>>;
    /**
     *
     * @type {TripRequestResponseJourneyLegStop}
     * @memberof TripRequestResponseJourneyLeg
     */
    destination?: TripRequestResponseJourneyLegStop;
    /**
     * The approximate distance in metres travelled to complete this journey leg.
     * @type {number}
     * @memberof TripRequestResponseJourneyLeg
     */
    distance?: number;
    /**
     * The approximate amount of time in seconds required to complete this journey leg.
     * @type {number}
     * @memberof TripRequestResponseJourneyLeg
     */
    duration?: number;
    /**
     * If the leg corresponds to a walking leg, this element contains walking directions.
     *
     * @type {Array<TripRequestResponseJourneyLegStopFootpathInfo>}
     * @memberof TripRequestResponseJourneyLeg
     */
    footPathInfo?: Array<TripRequestResponseJourneyLegStopFootpathInfo>;
    /**
     * Contains a number of additional informational messages that may be useful for travellers.
     * @type {Array<TripRequestResponseJourneyLegHintsInner>}
     * @memberof TripRequestResponseJourneyLeg
     */
    hints?: Array<TripRequestResponseJourneyLegHintsInner>;
    /**
     * Contains a number of service alert messages relating to this journey leg.
     * Information returned here is also available using the `add_info` API endpoint.
     *
     * @type {Array<TripRequestResponseJourneyLegStopInfo>}
     * @memberof TripRequestResponseJourneyLeg
     */
    infos?: Array<TripRequestResponseJourneyLegStopInfo>;
    /**
     *
     * @type {TripRequestResponseJourneyLegInterchange}
     * @memberof TripRequestResponseJourneyLeg
     */
    interchange?: TripRequestResponseJourneyLegInterchange;
    /**
     * This indicates whether or not real-time data has been used to calculate the departure/arrival timestamps
     * @type {boolean}
     * @memberof TripRequestResponseJourneyLeg
     */
    isRealtimeControlled?: boolean;
    /**
     *
     * @type {TripRequestResponseJourneyLegStop}
     * @memberof TripRequestResponseJourneyLeg
     */
    origin?: TripRequestResponseJourneyLegStop;
    /**
     * Contains walking information for completing this journey leg.
     * @type {Array<TripRequestResponseJourneyLegPathDescription>}
     * @memberof TripRequestResponseJourneyLeg
     */
    pathDescriptions?: Array<TripRequestResponseJourneyLegPathDescription>;
    /**
     *
     * @type {TripRequestResponseJourneyLegProperties}
     * @memberof TripRequestResponseJourneyLeg
     */
    properties?: TripRequestResponseJourneyLegProperties;
    /**
     * This is a list of all stops that are made for this leg. It is sorted in order of its
     * stopping sequence. If the leg is a walking leg between two stops, then this will contain
     * these two stops in order.
     *
     * @type {Array<TripRequestResponseJourneyLegStop>}
     * @memberof TripRequestResponseJourneyLeg
     */
    stopSequence?: Array<TripRequestResponseJourneyLegStop>;
    /**
     *
     * @type {TripTransportation}
     * @memberof TripRequestResponseJourneyLeg
     */
    transportation?: TripTransportation;
}

/**
 * Check if a given object implements the TripRequestResponseJourneyLeg interface.
 */
export function instanceOfTripRequestResponseJourneyLeg(
    value: object
): value is TripRequestResponseJourneyLeg {
    return true;
}

export function TripRequestResponseJourneyLegFromJSON(json: any): TripRequestResponseJourneyLeg {
    return TripRequestResponseJourneyLegFromJSONTyped(json, false);
}

export function TripRequestResponseJourneyLegFromJSONTyped(
    json: any,
    ignoreDiscriminator: boolean
): TripRequestResponseJourneyLeg {
    if (json == null) {
        return json;
    }
    return {
        coords: json["coords"] == null ? undefined : json["coords"],
        destination:
            json["destination"] == null
                ? undefined
                : TripRequestResponseJourneyLegStopFromJSON(json["destination"]),
        distance: json["distance"] == null ? undefined : json["distance"],
        duration: json["duration"] == null ? undefined : json["duration"],
        footPathInfo:
            json["footPathInfo"] == null
                ? undefined
                : (json["footPathInfo"] as Array<any>).map(
                      TripRequestResponseJourneyLegStopFootpathInfoFromJSON
                  ),
        hints:
            json["hints"] == null
                ? undefined
                : (json["hints"] as Array<any>).map(
                      TripRequestResponseJourneyLegHintsInnerFromJSON
                  ),
        infos:
            json["infos"] == null
                ? undefined
                : (json["infos"] as Array<any>).map(TripRequestResponseJourneyLegStopInfoFromJSON),
        interchange:
            json["interchange"] == null
                ? undefined
                : TripRequestResponseJourneyLegInterchangeFromJSON(json["interchange"]),
        isRealtimeControlled:
            json["isRealtimeControlled"] == null ? undefined : json["isRealtimeControlled"],
        origin:
            json["origin"] == null
                ? undefined
                : TripRequestResponseJourneyLegStopFromJSON(json["origin"]),
        pathDescriptions:
            json["pathDescriptions"] == null
                ? undefined
                : (json["pathDescriptions"] as Array<any>).map(
                      TripRequestResponseJourneyLegPathDescriptionFromJSON
                  ),
        properties:
            json["properties"] == null
                ? undefined
                : TripRequestResponseJourneyLegPropertiesFromJSON(json["properties"]),
        stopSequence:
            json["stopSequence"] == null
                ? undefined
                : (json["stopSequence"] as Array<any>).map(
                      TripRequestResponseJourneyLegStopFromJSON
                  ),
        transportation:
            json["transportation"] == null
                ? undefined
                : TripTransportationFromJSON(json["transportation"]),
    };
}

export function TripRequestResponseJourneyLegToJSON(json: any): TripRequestResponseJourneyLeg {
    return TripRequestResponseJourneyLegToJSONTyped(json, false);
}

export function TripRequestResponseJourneyLegToJSONTyped(
    value?: TripRequestResponseJourneyLeg | null,
    ignoreDiscriminator: boolean = false
): any {
    if (value == null) {
        return value;
    }

    return {
        coords: value["coords"],
        destination: TripRequestResponseJourneyLegStopToJSON(value["destination"]),
        distance: value["distance"],
        duration: value["duration"],
        footPathInfo:
            value["footPathInfo"] == null
                ? undefined
                : (value["footPathInfo"] as Array<any>).map(
                      TripRequestResponseJourneyLegStopFootpathInfoToJSON
                  ),
        hints:
            value["hints"] == null
                ? undefined
                : (value["hints"] as Array<any>).map(TripRequestResponseJourneyLegHintsInnerToJSON),
        infos:
            value["infos"] == null
                ? undefined
                : (value["infos"] as Array<any>).map(TripRequestResponseJourneyLegStopInfoToJSON),
        interchange: TripRequestResponseJourneyLegInterchangeToJSON(value["interchange"]),
        isRealtimeControlled: value["isRealtimeControlled"],
        origin: TripRequestResponseJourneyLegStopToJSON(value["origin"]),
        pathDescriptions:
            value["pathDescriptions"] == null
                ? undefined
                : (value["pathDescriptions"] as Array<any>).map(
                      TripRequestResponseJourneyLegPathDescriptionToJSON
                  ),
        properties: TripRequestResponseJourneyLegPropertiesToJSON(value["properties"]),
        stopSequence:
            value["stopSequence"] == null
                ? undefined
                : (value["stopSequence"] as Array<any>).map(
                      TripRequestResponseJourneyLegStopToJSON
                  ),
        transportation: TripTransportationToJSON(value["transportation"]),
    };
}
