/* tslint:disable */
/* eslint-disable */
/**
 * Trip Planner
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 10.6.21.17
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
import type { TripRequestResponseMessage } from "./TripRequestResponseMessage";
import {
    TripRequestResponseMessageFromJSON,
    TripRequestResponseMessageFromJSONTyped,
    TripRequestResponseMessageToJSON,
    TripRequestResponseMessageToJSONTyped,
} from "./TripRequestResponseMessage";

/**
 * Includes system messages that may be relevant to this particular request.
 * @export
 * @interface TripRequestResponseSystemMessages
 */
export interface TripRequestResponseSystemMessages {
    /**
     * Contains zero or more messages.
     * @type {Array<TripRequestResponseMessage>}
     * @memberof TripRequestResponseSystemMessages
     */
    responseMessages?: Array<TripRequestResponseMessage>;
}

/**
 * Check if a given object implements the TripRequestResponseSystemMessages interface.
 */
export function instanceOfTripRequestResponseSystemMessages(
    value: object
): value is TripRequestResponseSystemMessages {
    return true;
}

export function TripRequestResponseSystemMessagesFromJSON(
    json: any
): TripRequestResponseSystemMessages {
    return TripRequestResponseSystemMessagesFromJSONTyped(json, false);
}

export function TripRequestResponseSystemMessagesFromJSONTyped(
    json: any,
    ignoreDiscriminator: boolean
): TripRequestResponseSystemMessages {
    if (json == null) {
        return json;
    }
    return {
        responseMessages:
            json["responseMessages"] == null
                ? undefined
                : (json["responseMessages"] as Array<any>).map(TripRequestResponseMessageFromJSON),
    };
}

export function TripRequestResponseSystemMessagesToJSON(
    json: any
): TripRequestResponseSystemMessages {
    return TripRequestResponseSystemMessagesToJSONTyped(json, false);
}

export function TripRequestResponseSystemMessagesToJSONTyped(
    value?: TripRequestResponseSystemMessages | null,
    ignoreDiscriminator: boolean = false
): any {
    if (value == null) {
        return value;
    }

    return {
        responseMessages:
            value["responseMessages"] == null
                ? undefined
                : (value["responseMessages"] as Array<any>).map(TripRequestResponseMessageToJSON),
    };
}
