/* tslint:disable */
/* eslint-disable */
/**
 * Trip Planner
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 10.6.21.17
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
/**
 * This includes information about the location in which this instruction takes place.
 *
 * @export
 * @interface TripRequestResponseJourneyLegStopFootpathInfoFootpathElemLocationLocation
 */
export interface TripRequestResponseJourneyLegStopFootpathInfoFootpathElemLocationLocation {
    /**
     * Contains exactly two values: the first value is the latitude, the second value is the longitude.
     * Although multiple instructions may reference the same location, this coordinate is specific
     * to this particular instruction.
     *
     * @type {Array<number>}
     * @memberof TripRequestResponseJourneyLegStopFootpathInfoFootpathElemLocationLocation
     */
    coord?: Array<number>;
    /**
     * This the unique ID for the stop in which this instruction occurs.
     * @type {string}
     * @memberof TripRequestResponseJourneyLegStopFootpathInfoFootpathElemLocationLocation
     */
    id?: string;
    /**
     * This is the type of location in which this instruction occurs.
     * @type {string}
     * @memberof TripRequestResponseJourneyLegStopFootpathInfoFootpathElemLocationLocation
     */
    type?: TripRequestResponseJourneyLegStopFootpathInfoFootpathElemLocationLocationTypeEnum;
}

/**
 * @export
 */
export const TripRequestResponseJourneyLegStopFootpathInfoFootpathElemLocationLocationTypeEnum = {
    Poi: "poi",
    Singlehouse: "singlehouse",
    Stop: "stop",
    Platform: "platform",
    Street: "street",
    Locality: "locality",
    Suburb: "suburb",
    Unknown: "unknown",
} as const;
export type TripRequestResponseJourneyLegStopFootpathInfoFootpathElemLocationLocationTypeEnum =
    (typeof TripRequestResponseJourneyLegStopFootpathInfoFootpathElemLocationLocationTypeEnum)[keyof typeof TripRequestResponseJourneyLegStopFootpathInfoFootpathElemLocationLocationTypeEnum];

/**
 * Check if a given object implements the TripRequestResponseJourneyLegStopFootpathInfoFootpathElemLocationLocation interface.
 */
export function instanceOfTripRequestResponseJourneyLegStopFootpathInfoFootpathElemLocationLocation(
    value: object
): value is TripRequestResponseJourneyLegStopFootpathInfoFootpathElemLocationLocation {
    return true;
}

export function TripRequestResponseJourneyLegStopFootpathInfoFootpathElemLocationLocationFromJSON(
    json: any
): TripRequestResponseJourneyLegStopFootpathInfoFootpathElemLocationLocation {
    return TripRequestResponseJourneyLegStopFootpathInfoFootpathElemLocationLocationFromJSONTyped(
        json,
        false
    );
}

export function TripRequestResponseJourneyLegStopFootpathInfoFootpathElemLocationLocationFromJSONTyped(
    json: any,
    ignoreDiscriminator: boolean
): TripRequestResponseJourneyLegStopFootpathInfoFootpathElemLocationLocation {
    if (json == null) {
        return json;
    }
    return {
        coord: json["coord"] == null ? undefined : json["coord"],
        id: json["id"] == null ? undefined : json["id"],
        type: json["type"] == null ? undefined : json["type"],
    };
}

export function TripRequestResponseJourneyLegStopFootpathInfoFootpathElemLocationLocationToJSON(
    json: any
): TripRequestResponseJourneyLegStopFootpathInfoFootpathElemLocationLocation {
    return TripRequestResponseJourneyLegStopFootpathInfoFootpathElemLocationLocationToJSONTyped(
        json,
        false
    );
}

export function TripRequestResponseJourneyLegStopFootpathInfoFootpathElemLocationLocationToJSONTyped(
    value?: TripRequestResponseJourneyLegStopFootpathInfoFootpathElemLocationLocation | null,
    ignoreDiscriminator: boolean = false
): any {
    if (value == null) {
        return value;
    }

    return {
        coord: value["coord"],
        id: value["id"],
        type: value["type"],
    };
}
