/* tslint:disable */
/* eslint-disable */
/**
 * Trip Planner
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 10.6.21.17
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
import type { AdditionalInfoResponseTimestamps } from "./AdditionalInfoResponseTimestamps";
import {
    AdditionalInfoResponseTimestampsFromJSON,
    AdditionalInfoResponseTimestampsFromJSONTyped,
    AdditionalInfoResponseTimestampsToJSON,
    AdditionalInfoResponseTimestampsToJSONTyped,
} from "./AdditionalInfoResponseTimestamps";

/**
 * This element describes a single information message that may be associated with a journey leg.
 * The data in this is similar to that from `add_info`, but is presented differently.
 *
 * @export
 * @interface TripRequestResponseJourneyLegStopInfo
 */
export interface TripRequestResponseJourneyLegStopInfo {
    /**
     * This is the descriptive alert content. It may contain HTML tags and/or HTML entities.
     *
     * @type {string}
     * @memberof TripRequestResponseJourneyLegStopInfo
     */
    content?: string;
    /**
     * This is a unique identifier for this particular service alert. Note that this same ID is used in
     * `add_info` for the same alert.
     *
     * @type {string}
     * @memberof TripRequestResponseJourneyLegStopInfo
     */
    id?: string;
    /**
     * This value indicates how important the service alert is. A value of `high` or `veryHigh` likely indicates that
     * the alert will correspond to an event that impacts the ability to travel for relevant users, while `low` or `veryLow`
     * might be more of an informational message.
     *
     * @type {string}
     * @memberof TripRequestResponseJourneyLegStopInfo
     */
    priority?: TripRequestResponseJourneyLegStopInfoPriorityEnum;
    /**
     * This is short summary that can be used as a heading for the alert content. It may contain HTML tags and/or HTML entities.
     *
     * @type {string}
     * @memberof TripRequestResponseJourneyLegStopInfo
     */
    subtitle?: string;
    /**
     *
     * @type {AdditionalInfoResponseTimestamps}
     * @memberof TripRequestResponseJourneyLegStopInfo
     */
    timestamps?: AdditionalInfoResponseTimestamps;
    /**
     * This field contains a URL that contains additional information about the alert. This value is equivalent to
     * the `infoLinkURL` value in `add_info`.
     *
     * @type {string}
     * @memberof TripRequestResponseJourneyLegStopInfo
     */
    url?: string;
    /**
     * This field contains a title that can be used when displaying the `url` URL. This value is equivalent to
     * the `infoLinkText` value in `add_info`.
     *
     * @type {string}
     * @memberof TripRequestResponseJourneyLegStopInfo
     */
    urlText?: string;
    /**
     * This number indicates the version of this alert. Initially when it is created it has version `1`, but if it is then
     * updated it will have a new `lastModification` value and the version will now be `2`.
     *
     * @type {number}
     * @memberof TripRequestResponseJourneyLegStopInfo
     */
    version?: number;
}

/**
 * @export
 */
export const TripRequestResponseJourneyLegStopInfoPriorityEnum = {
    VeryLow: "veryLow",
    Low: "low",
    Normal: "normal",
    High: "high",
    VeryHigh: "veryHigh",
} as const;
export type TripRequestResponseJourneyLegStopInfoPriorityEnum =
    (typeof TripRequestResponseJourneyLegStopInfoPriorityEnum)[keyof typeof TripRequestResponseJourneyLegStopInfoPriorityEnum];

/**
 * Check if a given object implements the TripRequestResponseJourneyLegStopInfo interface.
 */
export function instanceOfTripRequestResponseJourneyLegStopInfo(
    value: object
): value is TripRequestResponseJourneyLegStopInfo {
    return true;
}

export function TripRequestResponseJourneyLegStopInfoFromJSON(
    json: any
): TripRequestResponseJourneyLegStopInfo {
    return TripRequestResponseJourneyLegStopInfoFromJSONTyped(json, false);
}

export function TripRequestResponseJourneyLegStopInfoFromJSONTyped(
    json: any,
    ignoreDiscriminator: boolean
): TripRequestResponseJourneyLegStopInfo {
    if (json == null) {
        return json;
    }
    return {
        content: json["content"] == null ? undefined : json["content"],
        id: json["id"] == null ? undefined : json["id"],
        priority: json["priority"] == null ? undefined : json["priority"],
        subtitle: json["subtitle"] == null ? undefined : json["subtitle"],
        timestamps:
            json["timestamps"] == null
                ? undefined
                : AdditionalInfoResponseTimestampsFromJSON(json["timestamps"]),
        url: json["url"] == null ? undefined : json["url"],
        urlText: json["urlText"] == null ? undefined : json["urlText"],
        version: json["version"] == null ? undefined : json["version"],
    };
}

export function TripRequestResponseJourneyLegStopInfoToJSON(
    json: any
): TripRequestResponseJourneyLegStopInfo {
    return TripRequestResponseJourneyLegStopInfoToJSONTyped(json, false);
}

export function TripRequestResponseJourneyLegStopInfoToJSONTyped(
    value?: TripRequestResponseJourneyLegStopInfo | null,
    ignoreDiscriminator: boolean = false
): any {
    if (value == null) {
        return value;
    }

    return {
        content: value["content"],
        id: value["id"],
        priority: value["priority"],
        subtitle: value["subtitle"],
        timestamps: AdditionalInfoResponseTimestampsToJSON(value["timestamps"]),
        url: value["url"],
        urlText: value["urlText"],
        version: value["version"],
    };
}
