/* tslint:disable */
/* eslint-disable */
/**
 * Trip Planner
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 10.6.21.17
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
/**
 * This element contains information about where vehicles on this route terminate.
 *
 * @export
 * @interface TripTransportationDestination
 */
export interface TripTransportationDestination {
    /**
     * Contains a unique identifier (if available) of the destination for this route.
     *
     * @type {string}
     * @memberof TripTransportationDestination
     */
    id?: string;
    /**
     * This is the name of the destination for this route.
     *
     * @type {string}
     * @memberof TripTransportationDestination
     */
    name?: string;
}

/**
 * Check if a given object implements the TripTransportationDestination interface.
 */
export function instanceOfTripTransportationDestination(
    value: object
): value is TripTransportationDestination {
    return true;
}

export function TripTransportationDestinationFromJSON(json: any): TripTransportationDestination {
    return TripTransportationDestinationFromJSONTyped(json, false);
}

export function TripTransportationDestinationFromJSONTyped(
    json: any,
    ignoreDiscriminator: boolean
): TripTransportationDestination {
    if (json == null) {
        return json;
    }
    return {
        id: json["id"] == null ? undefined : json["id"],
        name: json["name"] == null ? undefined : json["name"],
    };
}

export function TripTransportationDestinationToJSON(json: any): TripTransportationDestination {
    return TripTransportationDestinationToJSONTyped(json, false);
}

export function TripTransportationDestinationToJSONTyped(
    value?: TripTransportationDestination | null,
    ignoreDiscriminator: boolean = false
): any {
    if (value == null) {
        return value;
    }

    return {
        id: value["id"],
        name: value["name"],
    };
}
