/* tslint:disable */
/* eslint-disable */
/**
 * Trip Planner
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 10.6.21.17
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
/**
 *
 * @export
 * @interface TripRequestResponseJourneyLegHintsInner
 */
export interface TripRequestResponseJourneyLegHintsInner {
    /**
     * Contains additional information that may be useful for travellers.
     *
     * @type {string}
     * @memberof TripRequestResponseJourneyLegHintsInner
     */
    infoText?: string;
}

/**
 * Check if a given object implements the TripRequestResponseJourneyLegHintsInner interface.
 */
export function instanceOfTripRequestResponseJourneyLegHintsInner(
    value: object
): value is TripRequestResponseJourneyLegHintsInner {
    return true;
}

export function TripRequestResponseJourneyLegHintsInnerFromJSON(
    json: any
): TripRequestResponseJourneyLegHintsInner {
    return TripRequestResponseJourneyLegHintsInnerFromJSONTyped(json, false);
}

export function TripRequestResponseJourneyLegHintsInnerFromJSONTyped(
    json: any,
    ignoreDiscriminator: boolean
): TripRequestResponseJourneyLegHintsInner {
    if (json == null) {
        return json;
    }
    return {
        infoText: json["infoText"] == null ? undefined : json["infoText"],
    };
}

export function TripRequestResponseJourneyLegHintsInnerToJSON(
    json: any
): TripRequestResponseJourneyLegHintsInner {
    return TripRequestResponseJourneyLegHintsInnerToJSONTyped(json, false);
}

export function TripRequestResponseJourneyLegHintsInnerToJSONTyped(
    value?: TripRequestResponseJourneyLegHintsInner | null,
    ignoreDiscriminator: boolean = false
): any {
    if (value == null) {
        return value;
    }

    return {
        infoText: value["infoText"],
    };
}
