/* tslint:disable */
/* eslint-disable */
/**
 * Trip Planner
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 10.6.21.17
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
/**
 * This object describes walking directions for interchanging between two consecutive legs. This
 * occurs in the case when there's only a small distance between two transit legs, not enough
 * to constitute a standalone walking leg.
 *
 * @export
 * @interface TripRequestResponseJourneyLegInterchange
 */
export interface TripRequestResponseJourneyLegInterchange {
    /**
     * This is a list of coordinates that makes up the path of the interchange.
     *
     * @type {Array<Array<number>>}
     * @memberof TripRequestResponseJourneyLegInterchange
     */
    coords?: Array<Array<number>>;
    /**
     * This is a description of the interchange.
     *
     * @type {string}
     * @memberof TripRequestResponseJourneyLegInterchange
     */
    desc?: string;
    /**
     * This indicates the mode of travel for the interchange. Both `99` and `100` indicate walking.
     *
     * @type {number}
     * @memberof TripRequestResponseJourneyLegInterchange
     */
    type?: number;
}

/**
 * Check if a given object implements the TripRequestResponseJourneyLegInterchange interface.
 */
export function instanceOfTripRequestResponseJourneyLegInterchange(
    value: object
): value is TripRequestResponseJourneyLegInterchange {
    return true;
}

export function TripRequestResponseJourneyLegInterchangeFromJSON(
    json: any
): TripRequestResponseJourneyLegInterchange {
    return TripRequestResponseJourneyLegInterchangeFromJSONTyped(json, false);
}

export function TripRequestResponseJourneyLegInterchangeFromJSONTyped(
    json: any,
    ignoreDiscriminator: boolean
): TripRequestResponseJourneyLegInterchange {
    if (json == null) {
        return json;
    }
    return {
        coords: json["coords"] == null ? undefined : json["coords"],
        desc: json["desc"] == null ? undefined : json["desc"],
        type: json["type"] == null ? undefined : json["type"],
    };
}

export function TripRequestResponseJourneyLegInterchangeToJSON(
    json: any
): TripRequestResponseJourneyLegInterchange {
    return TripRequestResponseJourneyLegInterchangeToJSONTyped(json, false);
}

export function TripRequestResponseJourneyLegInterchangeToJSONTyped(
    value?: TripRequestResponseJourneyLegInterchange | null,
    ignoreDiscriminator: boolean = false
): any {
    if (value == null) {
        return value;
    }

    return {
        coords: value["coords"],
        desc: value["desc"],
        type: value["type"],
    };
}
