/* tslint:disable */
/* eslint-disable */
/**
 * Trip Planner
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 10.6.21.17
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
import type { TripRequestResponseJourneyLegStopFootpathInfoFootpathElemLocationLocation } from "./TripRequestResponseJourneyLegStopFootpathInfoFootpathElemLocationLocation";
import {
    TripRequestResponseJourneyLegStopFootpathInfoFootpathElemLocationLocationFromJSON,
    TripRequestResponseJourneyLegStopFootpathInfoFootpathElemLocationLocationFromJSONTyped,
    TripRequestResponseJourneyLegStopFootpathInfoFootpathElemLocationLocationToJSON,
    TripRequestResponseJourneyLegStopFootpathInfoFootpathElemLocationLocationToJSONTyped,
} from "./TripRequestResponseJourneyLegStopFootpathInfoFootpathElemLocationLocation";

/**
 * This element describes a starting or finishing point for a walking instruction.
 * @export
 * @interface TripRequestResponseJourneyLegStopFootpathInfoFootpathElemLocation
 */
export interface TripRequestResponseJourneyLegStopFootpathInfoFootpathElemLocation {
    /**
     * This is an internal value used to group stops together.
     * @type {number}
     * @memberof TripRequestResponseJourneyLegStopFootpathInfoFootpathElemLocation
     */
    area?: number;
    /**
     * This is an identifier for this particular instruction / location, based on its location.
     *
     * @type {string}
     * @memberof TripRequestResponseJourneyLegStopFootpathInfoFootpathElemLocation
     */
    georef?: string;
    /**
     *
     * @type {TripRequestResponseJourneyLegStopFootpathInfoFootpathElemLocationLocation}
     * @memberof TripRequestResponseJourneyLegStopFootpathInfoFootpathElemLocation
     */
    location?: TripRequestResponseJourneyLegStopFootpathInfoFootpathElemLocationLocation;
    /**
     * If available, this is a platform number that relates to this instruction. It defaults to `0` if
     * there is no such information available.
     *
     * @type {number}
     * @memberof TripRequestResponseJourneyLegStopFootpathInfoFootpathElemLocation
     */
    platform?: number;
}

/**
 * Check if a given object implements the TripRequestResponseJourneyLegStopFootpathInfoFootpathElemLocation interface.
 */
export function instanceOfTripRequestResponseJourneyLegStopFootpathInfoFootpathElemLocation(
    value: object
): value is TripRequestResponseJourneyLegStopFootpathInfoFootpathElemLocation {
    return true;
}

export function TripRequestResponseJourneyLegStopFootpathInfoFootpathElemLocationFromJSON(
    json: any
): TripRequestResponseJourneyLegStopFootpathInfoFootpathElemLocation {
    return TripRequestResponseJourneyLegStopFootpathInfoFootpathElemLocationFromJSONTyped(
        json,
        false
    );
}

export function TripRequestResponseJourneyLegStopFootpathInfoFootpathElemLocationFromJSONTyped(
    json: any,
    ignoreDiscriminator: boolean
): TripRequestResponseJourneyLegStopFootpathInfoFootpathElemLocation {
    if (json == null) {
        return json;
    }
    return {
        area: json["area"] == null ? undefined : json["area"],
        georef: json["georef"] == null ? undefined : json["georef"],
        location:
            json["location"] == null
                ? undefined
                : TripRequestResponseJourneyLegStopFootpathInfoFootpathElemLocationLocationFromJSON(
                      json["location"]
                  ),
        platform: json["platform"] == null ? undefined : json["platform"],
    };
}

export function TripRequestResponseJourneyLegStopFootpathInfoFootpathElemLocationToJSON(
    json: any
): TripRequestResponseJourneyLegStopFootpathInfoFootpathElemLocation {
    return TripRequestResponseJourneyLegStopFootpathInfoFootpathElemLocationToJSONTyped(
        json,
        false
    );
}

export function TripRequestResponseJourneyLegStopFootpathInfoFootpathElemLocationToJSONTyped(
    value?: TripRequestResponseJourneyLegStopFootpathInfoFootpathElemLocation | null,
    ignoreDiscriminator: boolean = false
): any {
    if (value == null) {
        return value;
    }

    return {
        area: value["area"],
        georef: value["georef"],
        location: TripRequestResponseJourneyLegStopFootpathInfoFootpathElemLocationLocationToJSON(
            value["location"]
        ),
        platform: value["platform"],
    };
}
