/* tslint:disable */
/* eslint-disable */
/**
 * Trip Planner
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 10.6.21.17
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
import type { TripTransportationDestination } from "./TripTransportationDestination";
import {
    TripTransportationDestinationFromJSON,
    TripTransportationDestinationFromJSONTyped,
    TripTransportationDestinationToJSON,
    TripTransportationDestinationToJSONTyped,
} from "./TripTransportationDestination";
import type { RouteProduct } from "./RouteProduct";
import {
    RouteProductFromJSON,
    RouteProductFromJSONTyped,
    RouteProductToJSON,
    RouteProductToJSONTyped,
} from "./RouteProduct";
import type { TripTransportationOperator } from "./TripTransportationOperator";
import {
    TripTransportationOperatorFromJSON,
    TripTransportationOperatorFromJSONTyped,
    TripTransportationOperatorToJSON,
    TripTransportationOperatorToJSONTyped,
} from "./TripTransportationOperator";
import type { TripTransportationProperties } from "./TripTransportationProperties";
import {
    TripTransportationPropertiesFromJSON,
    TripTransportationPropertiesFromJSONTyped,
    TripTransportationPropertiesToJSON,
    TripTransportationPropertiesToJSONTyped,
} from "./TripTransportationProperties";

/**
 * This element describes a route, including information about its route number, usual destination,
 * route type and operator.
 *
 * @export
 * @interface TripTransportation
 */
export interface TripTransportation {
    /**
     * Contains a description of this route.
     *
     * @type {string}
     * @memberof TripTransportation
     */
    description?: string;
    /**
     *
     * @type {TripTransportationDestination}
     * @memberof TripTransportation
     */
    destination?: TripTransportationDestination;
    /**
     * Contains a very short name for the route.
     *
     * @type {string}
     * @memberof TripTransportation
     */
    disassembledName?: string;
    /**
     * Contains an ID for the icon that can be used for this route. Different values here are
     * used to differentiate differents types of the same route type. For example, private ferries
     * have a different wayfinding icon to ferries operated by Sydney Ferries.
     *
     * * `1`: Sydney Trains (product class `1`)
     * * `2`: Intercity Trains (product class `1`)
     * * `3`: Regional Trains (product class `1`)
     * * `19`: Temporary Trains (product class `1`)
     *
     * * `24`: Sydney Metro (product class `2`)
     *
     * * `13`: Sydney Light Rail (product class `4`)
     * * `20`: Temporary Light Rail (product class `4`)
     * * `21`: Newcastle Light Rail (product class `4`)
     *
     * * `4`: Blue Mountains Buses (product class `5`)
     * * `5`: Sydney Buses (product class `5`)
     * * `6`: Central Coast Buses (product class `5`)
     * * `14`: Temporary Buses (product class `5`)
     * * `15`: Hunter Buses (product class `5`)
     * * `23`: On Demand (product class `5`)
     * * `31`: Central West and Orana (product class `5`)
     * * `32`: Far West (product class `5`)
     * * `33`: New England North West (product class `5`)
     * * `34`: Newcastle and Hunter (product class `5`)
     * * `35`: North Coast (product class `5`)
     * * `36`: Riverina Murray (product class `5`)
     * * `37`: South East and Tablelands (product class `5`)
     * * `38`: Sydney and Surrounds (product class `5`)
     *
     * * `9`: Private Buses (product class `5`)
     * * `17`: Private Coaches (product class `5`)
     *
     * * `7`: Regional Coaches (product class `7`)
     * * `22`: Temporary Coaches (product class `7`)
     *
     * * `10`: Sydney Ferries (product class `9`)
     * * `11`: Newcastle Ferries (product class `9`)
     * * `12`: Private Ferries (product class `9`)
     * * `18`: Temporary Ferries (product class `9`)
     *
     * * `8`: School Buses (product class `11`)
     *
     * @type {number}
     * @memberof TripTransportation
     */
    iconId?: number;
    /**
     * This is an ID that uniquely identifies this route.
     *
     * @type {string}
     * @memberof TripTransportation
     */
    id?: string;
    /**
     * This contains the full name of the route.
     *
     * @type {string}
     * @memberof TripTransportation
     */
    name?: string;
    /**
     * Contains a short name for the route.
     *
     * @type {string}
     * @memberof TripTransportation
     */
    number?: string;
    /**
     *
     * @type {TripTransportationOperator}
     * @memberof TripTransportation
     */
    operator?: TripTransportationOperator;
    /**
     *
     * @type {RouteProduct}
     * @memberof TripTransportation
     */
    product?: RouteProduct;
    /**
     *
     * @type {TripTransportationProperties}
     * @memberof TripTransportation
     */
    properties?: TripTransportationProperties;
}

/**
 * Check if a given object implements the TripTransportation interface.
 */
export function instanceOfTripTransportation(value: object): value is TripTransportation {
    return true;
}

export function TripTransportationFromJSON(json: any): TripTransportation {
    return TripTransportationFromJSONTyped(json, false);
}

export function TripTransportationFromJSONTyped(
    json: any,
    ignoreDiscriminator: boolean
): TripTransportation {
    if (json == null) {
        return json;
    }
    return {
        description: json["description"] == null ? undefined : json["description"],
        destination:
            json["destination"] == null
                ? undefined
                : TripTransportationDestinationFromJSON(json["destination"]),
        disassembledName: json["disassembledName"] == null ? undefined : json["disassembledName"],
        iconId: json["iconId"] == null ? undefined : json["iconId"],
        id: json["id"] == null ? undefined : json["id"],
        name: json["name"] == null ? undefined : json["name"],
        number: json["number"] == null ? undefined : json["number"],
        operator:
            json["operator"] == null
                ? undefined
                : TripTransportationOperatorFromJSON(json["operator"]),
        product: json["product"] == null ? undefined : RouteProductFromJSON(json["product"]),
        properties:
            json["properties"] == null
                ? undefined
                : TripTransportationPropertiesFromJSON(json["properties"]),
    };
}

export function TripTransportationToJSON(json: any): TripTransportation {
    return TripTransportationToJSONTyped(json, false);
}

export function TripTransportationToJSONTyped(
    value?: TripTransportation | null,
    ignoreDiscriminator: boolean = false
): any {
    if (value == null) {
        return value;
    }

    return {
        description: value["description"],
        destination: TripTransportationDestinationToJSON(value["destination"]),
        disassembledName: value["disassembledName"],
        iconId: value["iconId"],
        id: value["id"],
        name: value["name"],
        number: value["number"],
        operator: TripTransportationOperatorToJSON(value["operator"]),
        product: RouteProductToJSON(value["product"]),
        properties: TripTransportationPropertiesToJSON(value["properties"]),
    };
}
