/* tslint:disable */
/* eslint-disable */
/**
 * Trip Planner
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 10.6.21.17
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
import type { TripRequestResponseJourneyLeg } from "./TripRequestResponseJourneyLeg";
import {
    TripRequestResponseJourneyLegFromJSON,
    TripRequestResponseJourneyLegFromJSONTyped,
    TripRequestResponseJourneyLegToJSON,
    TripRequestResponseJourneyLegToJSONTyped,
} from "./TripRequestResponseJourneyLeg";

/**
 * This element describes a single journey returned by `trip`
 * @export
 * @interface TripRequestResponseJourney
 */
export interface TripRequestResponseJourney {
    /**
     * XXX
     * @type {boolean}
     * @memberof TripRequestResponseJourney
     */
    isAdditional?: boolean;
    /**
     * This element contains one or more legs that constitute the trip.
     * @type {Array<TripRequestResponseJourneyLeg>}
     * @memberof TripRequestResponseJourney
     */
    legs?: Array<TripRequestResponseJourneyLeg>;
    /**
     * XXX
     * @type {number}
     * @memberof TripRequestResponseJourney
     */
    rating?: number;
}

/**
 * Check if a given object implements the TripRequestResponseJourney interface.
 */
export function instanceOfTripRequestResponseJourney(
    value: object
): value is TripRequestResponseJourney {
    return true;
}

export function TripRequestResponseJourneyFromJSON(json: any): TripRequestResponseJourney {
    return TripRequestResponseJourneyFromJSONTyped(json, false);
}

export function TripRequestResponseJourneyFromJSONTyped(
    json: any,
    ignoreDiscriminator: boolean
): TripRequestResponseJourney {
    if (json == null) {
        return json;
    }
    return {
        isAdditional: json["isAdditional"] == null ? undefined : json["isAdditional"],
        legs:
            json["legs"] == null
                ? undefined
                : (json["legs"] as Array<any>).map(TripRequestResponseJourneyLegFromJSON),
        rating: json["rating"] == null ? undefined : json["rating"],
    };
}

export function TripRequestResponseJourneyToJSON(json: any): TripRequestResponseJourney {
    return TripRequestResponseJourneyToJSONTyped(json, false);
}

export function TripRequestResponseJourneyToJSONTyped(
    value?: TripRequestResponseJourney | null,
    ignoreDiscriminator: boolean = false
): any {
    if (value == null) {
        return value;
    }

    return {
        isAdditional: value["isAdditional"],
        legs:
            value["legs"] == null
                ? undefined
                : (value["legs"] as Array<any>).map(TripRequestResponseJourneyLegToJSON),
        rating: value["rating"],
    };
}
