/* tslint:disable */
/* eslint-disable */
/**
 * Trip Planner
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 10.6.21.17
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
import type { TripRequestResponseJourneyLegStopFootpathInfoFootpathElemLocation } from "./TripRequestResponseJourneyLegStopFootpathInfoFootpathElemLocation";
import {
    TripRequestResponseJourneyLegStopFootpathInfoFootpathElemLocationFromJSON,
    TripRequestResponseJourneyLegStopFootpathInfoFootpathElemLocationFromJSONTyped,
    TripRequestResponseJourneyLegStopFootpathInfoFootpathElemLocationToJSON,
    TripRequestResponseJourneyLegStopFootpathInfoFootpathElemLocationToJSONTyped,
} from "./TripRequestResponseJourneyLegStopFootpathInfoFootpathElemLocation";

/**
 * The element describes a single walking instruction.
 * @export
 * @interface TripRequestResponseJourneyLegStopFootpathInfoFootpathElem
 */
export interface TripRequestResponseJourneyLegStopFootpathInfoFootpathElem {
    /**
     * Contains additional information about this instruction, but is generally unused.
     *
     * @type {string}
     * @memberof TripRequestResponseJourneyLegStopFootpathInfoFootpathElem
     */
    description?: string;
    /**
     *
     * @type {TripRequestResponseJourneyLegStopFootpathInfoFootpathElemLocation}
     * @memberof TripRequestResponseJourneyLegStopFootpathInfoFootpathElem
     */
    destination?: TripRequestResponseJourneyLegStopFootpathInfoFootpathElemLocation;
    /**
     * Indicates the direction of travel for this instruction. Generally a ramp, escalator
     * or stairs will go `UP` or `DOWN` to a different floor. This value will be `LEVEL` when
     * the `type` field is also `LEVEL`.
     *
     * @type {string}
     * @memberof TripRequestResponseJourneyLegStopFootpathInfoFootpathElem
     */
    level?: TripRequestResponseJourneyLegStopFootpathInfoFootpathElemLevelEnum;
    /**
     * Indicates the floor number the instruction is starting from. If the `type` is `LEVEL`,
     * then the `levelFrom` and `levelTo` values should be the same.
     *
     * @type {number}
     * @memberof TripRequestResponseJourneyLegStopFootpathInfoFootpathElem
     */
    levelFrom?: number;
    /**
     * Indicates the floor number the instruction ends of. If the `type` is `LEVEL`,
     * then the `levelFrom` and `levelTo` values should be the same.
     *
     * @type {number}
     * @memberof TripRequestResponseJourneyLegStopFootpathInfoFootpathElem
     */
    levelTo?: number;
    /**
     *
     * @type {TripRequestResponseJourneyLegStopFootpathInfoFootpathElemLocation}
     * @memberof TripRequestResponseJourneyLegStopFootpathInfoFootpathElem
     */
    origin?: TripRequestResponseJourneyLegStopFootpathInfoFootpathElemLocation;
    /**
     * This indicates the type of "terrain" for this instruction. `LEVEL` indicates a normal
     * flat surface.
     *
     * @type {string}
     * @memberof TripRequestResponseJourneyLegStopFootpathInfoFootpathElem
     */
    type?: TripRequestResponseJourneyLegStopFootpathInfoFootpathElemTypeEnum;
}

/**
 * @export
 */
export const TripRequestResponseJourneyLegStopFootpathInfoFootpathElemLevelEnum = {
    Down: "DOWN",
    Level: "LEVEL",
    Up: "UP",
} as const;
export type TripRequestResponseJourneyLegStopFootpathInfoFootpathElemLevelEnum =
    (typeof TripRequestResponseJourneyLegStopFootpathInfoFootpathElemLevelEnum)[keyof typeof TripRequestResponseJourneyLegStopFootpathInfoFootpathElemLevelEnum];

/**
 * @export
 */
export const TripRequestResponseJourneyLegStopFootpathInfoFootpathElemTypeEnum = {
    Escalator: "ESCALATOR",
    Elevator: "ELEVATOR",
    Stairs: "STAIRS",
    Level: "LEVEL",
    Ramp: "RAMP",
} as const;
export type TripRequestResponseJourneyLegStopFootpathInfoFootpathElemTypeEnum =
    (typeof TripRequestResponseJourneyLegStopFootpathInfoFootpathElemTypeEnum)[keyof typeof TripRequestResponseJourneyLegStopFootpathInfoFootpathElemTypeEnum];

/**
 * Check if a given object implements the TripRequestResponseJourneyLegStopFootpathInfoFootpathElem interface.
 */
export function instanceOfTripRequestResponseJourneyLegStopFootpathInfoFootpathElem(
    value: object
): value is TripRequestResponseJourneyLegStopFootpathInfoFootpathElem {
    return true;
}

export function TripRequestResponseJourneyLegStopFootpathInfoFootpathElemFromJSON(
    json: any
): TripRequestResponseJourneyLegStopFootpathInfoFootpathElem {
    return TripRequestResponseJourneyLegStopFootpathInfoFootpathElemFromJSONTyped(json, false);
}

export function TripRequestResponseJourneyLegStopFootpathInfoFootpathElemFromJSONTyped(
    json: any,
    ignoreDiscriminator: boolean
): TripRequestResponseJourneyLegStopFootpathInfoFootpathElem {
    if (json == null) {
        return json;
    }
    return {
        description: json["description"] == null ? undefined : json["description"],
        destination:
            json["destination"] == null
                ? undefined
                : TripRequestResponseJourneyLegStopFootpathInfoFootpathElemLocationFromJSON(
                      json["destination"]
                  ),
        level: json["level"] == null ? undefined : json["level"],
        levelFrom: json["levelFrom"] == null ? undefined : json["levelFrom"],
        levelTo: json["levelTo"] == null ? undefined : json["levelTo"],
        origin:
            json["origin"] == null
                ? undefined
                : TripRequestResponseJourneyLegStopFootpathInfoFootpathElemLocationFromJSON(
                      json["origin"]
                  ),
        type: json["type"] == null ? undefined : json["type"],
    };
}

export function TripRequestResponseJourneyLegStopFootpathInfoFootpathElemToJSON(
    json: any
): TripRequestResponseJourneyLegStopFootpathInfoFootpathElem {
    return TripRequestResponseJourneyLegStopFootpathInfoFootpathElemToJSONTyped(json, false);
}

export function TripRequestResponseJourneyLegStopFootpathInfoFootpathElemToJSONTyped(
    value?: TripRequestResponseJourneyLegStopFootpathInfoFootpathElem | null,
    ignoreDiscriminator: boolean = false
): any {
    if (value == null) {
        return value;
    }

    return {
        description: value["description"],
        destination: TripRequestResponseJourneyLegStopFootpathInfoFootpathElemLocationToJSON(
            value["destination"]
        ),
        level: value["level"],
        levelFrom: value["levelFrom"],
        levelTo: value["levelTo"],
        origin: TripRequestResponseJourneyLegStopFootpathInfoFootpathElemLocationToJSON(
            value["origin"]
        ),
        type: value["type"],
    };
}
