/* tslint:disable */
/* eslint-disable */
/**
 * Trip Planner
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 10.6.21.17
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
/**
 * Not currently used.
 * @export
 * @interface TripRequestResponseJourneyFareZone
 */
export interface TripRequestResponseJourneyFareZone {
    /**
     * Not currently used.
     * @type {number}
     * @memberof TripRequestResponseJourneyFareZone
     */
    fromLeg?: number;
    /**
     * Not currently used.
     * @type {string}
     * @memberof TripRequestResponseJourneyFareZone
     */
    net?: string;
    /**
     * Not currently used.
     * @type {string}
     * @memberof TripRequestResponseJourneyFareZone
     */
    neutralZone?: string;
    /**
     * Not currently used.
     * @type {number}
     * @memberof TripRequestResponseJourneyFareZone
     */
    toLeg?: number;
}

/**
 * Check if a given object implements the TripRequestResponseJourneyFareZone interface.
 */
export function instanceOfTripRequestResponseJourneyFareZone(
    value: object
): value is TripRequestResponseJourneyFareZone {
    return true;
}

export function TripRequestResponseJourneyFareZoneFromJSON(
    json: any
): TripRequestResponseJourneyFareZone {
    return TripRequestResponseJourneyFareZoneFromJSONTyped(json, false);
}

export function TripRequestResponseJourneyFareZoneFromJSONTyped(
    json: any,
    ignoreDiscriminator: boolean
): TripRequestResponseJourneyFareZone {
    if (json == null) {
        return json;
    }
    return {
        fromLeg: json["fromLeg"] == null ? undefined : json["fromLeg"],
        net: json["net"] == null ? undefined : json["net"],
        neutralZone: json["neutralZone"] == null ? undefined : json["neutralZone"],
        toLeg: json["toLeg"] == null ? undefined : json["toLeg"],
    };
}

export function TripRequestResponseJourneyFareZoneToJSON(
    json: any
): TripRequestResponseJourneyFareZone {
    return TripRequestResponseJourneyFareZoneToJSONTyped(json, false);
}

export function TripRequestResponseJourneyFareZoneToJSONTyped(
    value?: TripRequestResponseJourneyFareZone | null,
    ignoreDiscriminator: boolean = false
): any {
    if (value == null) {
        return value;
    }

    return {
        fromLeg: value["fromLeg"],
        net: value["net"],
        neutralZone: value["neutralZone"],
        toLeg: value["toLeg"],
    };
}
