/* tslint:disable */
/* eslint-disable */
/**
 * Trip Planner
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 10.6.21.17
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
/**
 * Contains additional information about this journey leg, such as wheelchair accessibility information.
 *
 * @export
 * @interface TripRequestResponseJourneyLegProperties
 */
export interface TripRequestResponseJourneyLegProperties {
    /**
     * XXX
     * @type {string}
     * @memberof TripRequestResponseJourneyLegProperties
     */
    dIFFERENTFARES?: string;
    /**
     * This indicates whether or not the vehicle is wheelchair accessible.
     * @type {string}
     * @memberof TripRequestResponseJourneyLegProperties
     */
    planLowFloorVehicle?: string;
    /**
     * This indicates whether or not the stop is wheelchair accessible.
     * @type {string}
     * @memberof TripRequestResponseJourneyLegProperties
     */
    planWheelChairAccess?: string;
    /**
     * XXX seen a value of SUPPLEMENT for ferry route
     *
     * @type {string}
     * @memberof TripRequestResponseJourneyLegProperties
     */
    lineType?: string;
    /**
     * This value is not currently in use.
     * @type {Array<string>}
     * @memberof TripRequestResponseJourneyLegProperties
     */
    vehicleAccess?: Array<string>;
}

/**
 * Check if a given object implements the TripRequestResponseJourneyLegProperties interface.
 */
export function instanceOfTripRequestResponseJourneyLegProperties(
    value: object
): value is TripRequestResponseJourneyLegProperties {
    return true;
}

export function TripRequestResponseJourneyLegPropertiesFromJSON(
    json: any
): TripRequestResponseJourneyLegProperties {
    return TripRequestResponseJourneyLegPropertiesFromJSONTyped(json, false);
}

export function TripRequestResponseJourneyLegPropertiesFromJSONTyped(
    json: any,
    ignoreDiscriminator: boolean
): TripRequestResponseJourneyLegProperties {
    if (json == null) {
        return json;
    }
    return {
        dIFFERENTFARES: json["DIFFERENT_FARES"] == null ? undefined : json["DIFFERENT_FARES"],
        planLowFloorVehicle:
            json["PlanLowFloorVehicle"] == null ? undefined : json["PlanLowFloorVehicle"],
        planWheelChairAccess:
            json["PlanWheelChairAccess"] == null ? undefined : json["PlanWheelChairAccess"],
        lineType: json["lineType"] == null ? undefined : json["lineType"],
        vehicleAccess: json["vehicleAccess"] == null ? undefined : json["vehicleAccess"],
    };
}

export function TripRequestResponseJourneyLegPropertiesToJSON(
    json: any
): TripRequestResponseJourneyLegProperties {
    return TripRequestResponseJourneyLegPropertiesToJSONTyped(json, false);
}

export function TripRequestResponseJourneyLegPropertiesToJSONTyped(
    value?: TripRequestResponseJourneyLegProperties | null,
    ignoreDiscriminator: boolean = false
): any {
    if (value == null) {
        return value;
    }

    return {
        DIFFERENT_FARES: value["dIFFERENTFARES"],
        PlanLowFloorVehicle: value["planLowFloorVehicle"],
        PlanWheelChairAccess: value["planWheelChairAccess"],
        lineType: value["lineType"],
        vehicleAccess: value["vehicleAccess"],
    };
}
