/* tslint:disable */
/* eslint-disable */
/**
 * Trip Planner
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 10.6.21.17
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
import type { TripRequestResponseJourneyLegStopDownload } from "./TripRequestResponseJourneyLegStopDownload";
import {
    TripRequestResponseJourneyLegStopDownloadFromJSON,
    TripRequestResponseJourneyLegStopDownloadFromJSONTyped,
    TripRequestResponseJourneyLegStopDownloadToJSON,
    TripRequestResponseJourneyLegStopDownloadToJSONTyped,
} from "./TripRequestResponseJourneyLegStopDownload";

/**
 * Contains additional information about this stop, such as wheelchair accessibility information.
 *
 * @export
 * @interface TripRequestResponseJourneyLegStopProperties
 */
export interface TripRequestResponseJourneyLegStopProperties {
    /**
     * Indicates if there is wheelchair access available at this stop.
     *
     * @type {string}
     * @memberof TripRequestResponseJourneyLegStopProperties
     */
    wheelchairAccess?: TripRequestResponseJourneyLegStopPropertiesWheelchairAccessEnum;
    /**
     * Describes a list of downloadable files relevant to this location.
     *
     * @type {Array<TripRequestResponseJourneyLegStopDownload>}
     * @memberof TripRequestResponseJourneyLegStopProperties
     */
    downloads?: Array<TripRequestResponseJourneyLegStopDownload>;
}

/**
 * @export
 */
export const TripRequestResponseJourneyLegStopPropertiesWheelchairAccessEnum = {
    True: "true",
    False: "false",
} as const;
export type TripRequestResponseJourneyLegStopPropertiesWheelchairAccessEnum =
    (typeof TripRequestResponseJourneyLegStopPropertiesWheelchairAccessEnum)[keyof typeof TripRequestResponseJourneyLegStopPropertiesWheelchairAccessEnum];

/**
 * Check if a given object implements the TripRequestResponseJourneyLegStopProperties interface.
 */
export function instanceOfTripRequestResponseJourneyLegStopProperties(
    value: object
): value is TripRequestResponseJourneyLegStopProperties {
    return true;
}

export function TripRequestResponseJourneyLegStopPropertiesFromJSON(
    json: any
): TripRequestResponseJourneyLegStopProperties {
    return TripRequestResponseJourneyLegStopPropertiesFromJSONTyped(json, false);
}

export function TripRequestResponseJourneyLegStopPropertiesFromJSONTyped(
    json: any,
    ignoreDiscriminator: boolean
): TripRequestResponseJourneyLegStopProperties {
    if (json == null) {
        return json;
    }
    return {
        wheelchairAccess: json["WheelchairAccess"] == null ? undefined : json["WheelchairAccess"],
        downloads:
            json["downloads"] == null
                ? undefined
                : (json["downloads"] as Array<any>).map(
                      TripRequestResponseJourneyLegStopDownloadFromJSON
                  ),
    };
}

export function TripRequestResponseJourneyLegStopPropertiesToJSON(
    json: any
): TripRequestResponseJourneyLegStopProperties {
    return TripRequestResponseJourneyLegStopPropertiesToJSONTyped(json, false);
}

export function TripRequestResponseJourneyLegStopPropertiesToJSONTyped(
    value?: TripRequestResponseJourneyLegStopProperties | null,
    ignoreDiscriminator: boolean = false
): any {
    if (value == null) {
        return value;
    }

    return {
        WheelchairAccess: value["wheelchairAccess"],
        downloads:
            value["downloads"] == null
                ? undefined
                : (value["downloads"] as Array<any>).map(
                      TripRequestResponseJourneyLegStopDownloadToJSON
                  ),
    };
}
