/* tslint:disable */
/* eslint-disable */
/**
 * Trip Planner
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 10.6.21.17
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
/**
 * Contains a single instruction for completing a walking leg associated with a journey leg.
 * @export
 * @interface TripRequestResponseJourneyLegPathDescription
 */
export interface TripRequestResponseJourneyLegPathDescription {
    /**
     * Contains exactly two values: the first value is the latitude, the second value is the longitude. This is the
     * location where the instruction occurs.
     *
     * @type {Array<number>}
     * @memberof TripRequestResponseJourneyLegPathDescription
     */
    coord?: Array<number>;
    /**
     * This is the cumulative distance travelled in metres at the point of this step.
     * @type {number}
     * @memberof TripRequestResponseJourneyLegPathDescription
     */
    cumDistance?: number;
    /**
     * This is the cumulative duration in seconds at the point of this step.
     *
     * @type {number}
     * @memberof TripRequestResponseJourneyLegPathDescription
     */
    cumDuration?: number;
    /**
     * This is the distance travelled in this step in metres.
     *
     * @type {number}
     * @memberof TripRequestResponseJourneyLegPathDescription
     */
    distance?: number;
    /**
     * This is the distance travelled downward in this step in metres
     *
     * @type {number}
     * @memberof TripRequestResponseJourneyLegPathDescription
     */
    distanceDown?: number;
    /**
     * This is the distance travelled upward in this step in metres
     *
     * @type {number}
     * @memberof TripRequestResponseJourneyLegPathDescription
     */
    distanceUp?: number;
    /**
     * This is the duration of this step in seconds.
     *
     * @type {number}
     * @memberof TripRequestResponseJourneyLegPathDescription
     */
    duration?: number;
    /**
     * This field enables you to retrieve multiple coordinates from the `coords` property, starting from this index.
     *
     * @type {number}
     * @memberof TripRequestResponseJourneyLegPathDescription
     */
    fromCoordsIndex?: number;
    /**
     * Indicates what you have to do (in addition the turn `turnDirection`) to execute this step of the path description.
     *
     * @type {string}
     * @memberof TripRequestResponseJourneyLegPathDescription
     */
    manoeuvre?: TripRequestResponseJourneyLegPathDescriptionManoeuvreEnum;
    /**
     * This is a specific description of what to do. In some cases, this information is required in addition to the
     * other properties provided in this step.
     *
     * @type {string}
     * @memberof TripRequestResponseJourneyLegPathDescription
     */
    name?: string;
    /**
     * The direction in degrees (0-359) of the skyDirection
     * @type {number}
     * @memberof TripRequestResponseJourneyLegPathDescription
     */
    skyDirection?: number;
    /**
     * This field enables you to retrieve multiple coordinates from the `coords` property, ending at this index.
     *
     * @type {number}
     * @memberof TripRequestResponseJourneyLegPathDescription
     */
    toCoordsIndex?: number;
    /**
     * Indicates the way you need to turn to execute this step of the path description.
     *
     * @type {string}
     * @memberof TripRequestResponseJourneyLegPathDescription
     */
    turnDirection?: TripRequestResponseJourneyLegPathDescriptionTurnDirectionEnum;
}

/**
 * @export
 */
export const TripRequestResponseJourneyLegPathDescriptionManoeuvreEnum = {
    Leave: "LEAVE",
    Keep: "KEEP",
    Turn: "TURN",
    Enter: "ENTER",
    Continue: "CONTINUE",
} as const;
export type TripRequestResponseJourneyLegPathDescriptionManoeuvreEnum =
    (typeof TripRequestResponseJourneyLegPathDescriptionManoeuvreEnum)[keyof typeof TripRequestResponseJourneyLegPathDescriptionManoeuvreEnum];

/**
 * @export
 */
export const TripRequestResponseJourneyLegPathDescriptionTurnDirectionEnum = {
    Unknown: "UNKNOWN",
    Straight: "STRAIGHT",
    Right: "RIGHT",
    Left: "LEFT",
    SlightRight: "SLIGHT_RIGHT",
    SlightLeft: "SLIGHT_LEFT",
    SharpLeft: "SHARP_LEFT",
    SharpRight: "SHARP_RIGHT",
} as const;
export type TripRequestResponseJourneyLegPathDescriptionTurnDirectionEnum =
    (typeof TripRequestResponseJourneyLegPathDescriptionTurnDirectionEnum)[keyof typeof TripRequestResponseJourneyLegPathDescriptionTurnDirectionEnum];

/**
 * Check if a given object implements the TripRequestResponseJourneyLegPathDescription interface.
 */
export function instanceOfTripRequestResponseJourneyLegPathDescription(
    value: object
): value is TripRequestResponseJourneyLegPathDescription {
    return true;
}

export function TripRequestResponseJourneyLegPathDescriptionFromJSON(
    json: any
): TripRequestResponseJourneyLegPathDescription {
    return TripRequestResponseJourneyLegPathDescriptionFromJSONTyped(json, false);
}

export function TripRequestResponseJourneyLegPathDescriptionFromJSONTyped(
    json: any,
    ignoreDiscriminator: boolean
): TripRequestResponseJourneyLegPathDescription {
    if (json == null) {
        return json;
    }
    return {
        coord: json["coord"] == null ? undefined : json["coord"],
        cumDistance: json["cumDistance"] == null ? undefined : json["cumDistance"],
        cumDuration: json["cumDuration"] == null ? undefined : json["cumDuration"],
        distance: json["distance"] == null ? undefined : json["distance"],
        distanceDown: json["distanceDown"] == null ? undefined : json["distanceDown"],
        distanceUp: json["distanceUp"] == null ? undefined : json["distanceUp"],
        duration: json["duration"] == null ? undefined : json["duration"],
        fromCoordsIndex: json["fromCoordsIndex"] == null ? undefined : json["fromCoordsIndex"],
        manoeuvre: json["manoeuvre"] == null ? undefined : json["manoeuvre"],
        name: json["name"] == null ? undefined : json["name"],
        skyDirection: json["skyDirection"] == null ? undefined : json["skyDirection"],
        toCoordsIndex: json["toCoordsIndex"] == null ? undefined : json["toCoordsIndex"],
        turnDirection: json["turnDirection"] == null ? undefined : json["turnDirection"],
    };
}

export function TripRequestResponseJourneyLegPathDescriptionToJSON(
    json: any
): TripRequestResponseJourneyLegPathDescription {
    return TripRequestResponseJourneyLegPathDescriptionToJSONTyped(json, false);
}

export function TripRequestResponseJourneyLegPathDescriptionToJSONTyped(
    value?: TripRequestResponseJourneyLegPathDescription | null,
    ignoreDiscriminator: boolean = false
): any {
    if (value == null) {
        return value;
    }

    return {
        coord: value["coord"],
        cumDistance: value["cumDistance"],
        cumDuration: value["cumDuration"],
        distance: value["distance"],
        distanceDown: value["distanceDown"],
        distanceUp: value["distanceUp"],
        duration: value["duration"],
        fromCoordsIndex: value["fromCoordsIndex"],
        manoeuvre: value["manoeuvre"],
        name: value["name"],
        skyDirection: value["skyDirection"],
        toCoordsIndex: value["toCoordsIndex"],
        turnDirection: value["turnDirection"],
    };
}
