/* tslint:disable */
/* eslint-disable */
/**
 * Trip Planner
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 10.6.21.17
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
/**
 * Contains additional properties about this route.
 *
 * @export
 * @interface TripTransportationProperties
 */
export interface TripTransportationProperties {
    /**
     * XXX
     * @type {boolean}
     * @memberof TripTransportationProperties
     */
    isTTB?: boolean;
    /**
     * This is an ID for this journey option.
     * @type {number}
     * @memberof TripTransportationProperties
     */
    tripCode?: number;
}

/**
 * Check if a given object implements the TripTransportationProperties interface.
 */
export function instanceOfTripTransportationProperties(
    value: object
): value is TripTransportationProperties {
    return true;
}

export function TripTransportationPropertiesFromJSON(json: any): TripTransportationProperties {
    return TripTransportationPropertiesFromJSONTyped(json, false);
}

export function TripTransportationPropertiesFromJSONTyped(
    json: any,
    ignoreDiscriminator: boolean
): TripTransportationProperties {
    if (json == null) {
        return json;
    }
    return {
        isTTB: json["isTTB"] == null ? undefined : json["isTTB"],
        tripCode: json["tripCode"] == null ? undefined : json["tripCode"],
    };
}

export function TripTransportationPropertiesToJSON(json: any): TripTransportationProperties {
    return TripTransportationPropertiesToJSONTyped(json, false);
}

export function TripTransportationPropertiesToJSONTyped(
    value?: TripTransportationProperties | null,
    ignoreDiscriminator: boolean = false
): any {
    if (value == null) {
        return value;
    }

    return {
        isTTB: value["isTTB"],
        tripCode: value["tripCode"],
    };
}
