/* tslint:disable */
/* eslint-disable */
/**
 * Trip Planner
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 10.6.21.17
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
import type { TripRequestResponseSystemMessages } from "./TripRequestResponseSystemMessages";
import {
    TripRequestResponseSystemMessagesFromJSON,
    TripRequestResponseSystemMessagesFromJSONTyped,
    TripRequestResponseSystemMessagesToJSON,
    TripRequestResponseSystemMessagesToJSONTyped,
} from "./TripRequestResponseSystemMessages";
import type { TripRequestResponseJourney } from "./TripRequestResponseJourney";
import {
    TripRequestResponseJourneyFromJSON,
    TripRequestResponseJourneyFromJSONTyped,
    TripRequestResponseJourneyToJSON,
    TripRequestResponseJourneyToJSONTyped,
} from "./TripRequestResponseJourney";
import type { ApiErrorResponse } from "./ApiErrorResponse";
import {
    ApiErrorResponseFromJSON,
    ApiErrorResponseFromJSONTyped,
    ApiErrorResponseToJSON,
    ApiErrorResponseToJSONTyped,
} from "./ApiErrorResponse";

/**
 * This element contains the response from an `trip` request.
 * @export
 * @interface TripRequestResponse
 */
export interface TripRequestResponse {
    /**
     *
     * @type {ApiErrorResponse}
     * @memberof TripRequestResponse
     */
    error?: ApiErrorResponse;
    /**
     * Contains zero or more journeys found based on the input parameters.
     * @type {Array<TripRequestResponseJourney>}
     * @memberof TripRequestResponse
     */
    journeys?: Array<TripRequestResponseJourney>;
    /**
     *
     * @type {TripRequestResponseSystemMessages}
     * @memberof TripRequestResponse
     */
    systemMessages?: TripRequestResponseSystemMessages;
    /**
     * The version of the API that provided the response. Note that if this value is different to above, then the returned data may be
     * different than expected. You can set the expected version using the `version` request parameter.
     *
     * @type {string}
     * @memberof TripRequestResponse
     */
    version?: string;
}

/**
 * Check if a given object implements the TripRequestResponse interface.
 */
export function instanceOfTripRequestResponse(value: object): value is TripRequestResponse {
    return true;
}

export function TripRequestResponseFromJSON(json: any): TripRequestResponse {
    return TripRequestResponseFromJSONTyped(json, false);
}

export function TripRequestResponseFromJSONTyped(
    json: any,
    ignoreDiscriminator: boolean
): TripRequestResponse {
    if (json == null) {
        return json;
    }
    return {
        error: json["error"] == null ? undefined : ApiErrorResponseFromJSON(json["error"]),
        journeys:
            json["journeys"] == null
                ? undefined
                : (json["journeys"] as Array<any>).map(TripRequestResponseJourneyFromJSON),
        systemMessages:
            json["systemMessages"] == null
                ? undefined
                : TripRequestResponseSystemMessagesFromJSON(json["systemMessages"]),
        version: json["version"] == null ? undefined : json["version"],
    };
}

export function TripRequestResponseToJSON(json: any): TripRequestResponse {
    return TripRequestResponseToJSONTyped(json, false);
}

export function TripRequestResponseToJSONTyped(
    value?: TripRequestResponse | null,
    ignoreDiscriminator: boolean = false
): any {
    if (value == null) {
        return value;
    }

    return {
        error: ApiErrorResponseToJSON(value["error"]),
        journeys:
            value["journeys"] == null
                ? undefined
                : (value["journeys"] as Array<any>).map(TripRequestResponseJourneyToJSON),
        systemMessages: TripRequestResponseSystemMessagesToJSON(value["systemMessages"]),
        version: value["version"],
    };
}
